var ttll = {
    "Front Opposite":["(U') R2' U2' R2 U' R2' U R2 U' R2' U' R2", "(U) R U2' R U R2' U R U' R U' R2' U' R U R' / (U') R2 U R' U' R' U R U2 R' U' R U R U2' R2'", "(U2) R2' U R2 U R2' U2' R2", "(U) R U' R' U R2 U R' U R' U' R2' U' R' U2 R'", "R U' R' U' R U2' R' U2 R U2' R' U R U R' / (U) R2 U R2 U' R2 U2 R2 U R2 U' R2", "(U2) R U' R' U2 R' U2 R2 U R' U' R' U2 R", "(U) R U' R' U R U2' R' U' R U R'", "(U') R U R' U R U R' U R U' R' U R U R' U R U R' / R U' R2 U2 R' U R' U' R U2 R2 U R' / R2' U2' S' R2 S U' S' R2' S U' R2'", "(U) S R2' S' U' R2 U' R2' U R2", "R2' U2' R2 U' S R2' S' U' R2", "(U) R' U' R2 U' R2' U2' R U R U2' R' / R2' U' R2 U R2' U S R2 S'", "R2' U2' R2 U' R2' U' R2"],
    "Right Opposite":["(U') D R' U2 R U R' U2 R2 U2 R' U' R U' R2 U' R D' / R2 U2' R2' U' R U R' U' R U' R2 U' D R' U R D' / (U) D R' U' R U D' R2 U R' U R U' R' U R2' U2 R2", "(U') R U2' R' U2 R U2' R2' F' R U R U' R' F", "(U') D R2' U2' R2 U S R2' S' U R2 D'", "(U2) D R U R U' R' U2 R' U2 R2 U R' U' R' D' / (U) R' D' R U' R2' D' r U2 r' D R U2 D R", "(U2) D R' U R U' R' U2 R U R' U' R D'", "(U') D R2' U2 R2 U R2' U R2 D'", "(U2) R U' R' F' U' L' U2 L U F R U R'", "D R U R U' R2 U2 R U2 R U R' U' R' D'", "R2' F2 U2' R2 U' R2' U' F2 R2", "(U2) R2' F2 U R2 U R2' U2' F2 R2", "(U) D R2' U' R2 U' R2' U2 R2 D'", "(U') F' R U R' U' R' F R2 U2' R' U2 R U2' R'"],
	"Double Opposite":["(U2) R' F R F' R' F R F' R' F R F'", "R' U' R' U R2 D' R U2 R' U2 R U' R' D R' / R' U2 D' R U R' U D R U2 R' U' R U' R' U2 R", "R' D R U' R D' R' U2 R D R' U R' D' R", "D F' U R' U R U2 R' F U2 F' R F R' U' R D / (U) R U2' R' U R F R' U R U2' R' U R U F' U2' R' / F' R U R' U R' D' R U R' D R U' R U2 R' F / (U') R2 U' F2 U' F2 R2 U2 R2 D R2 D'", "(U') D R2' U' F2 U' R2 U R2' U F2 R2 D' / F2 U' r2 U' r2 U r2 U r2 F2", "z UD R U' R2' D' R2 U R2' D R U'D' z' / D' R U2 D R U' R' U2 R U' R' U D' R' D R U R'", "R2 U B2 U R2' U' R2 U' B2 R2' / R2 D r2' U r2 U' r2' U' r2 U D' R2'", "R2 D R2' U' D' F2 R2 U' R2' U' F2", "R2 B2 U R2' U R2 U' B2 U' R2' / F2 U' R2 U2 R2 U' R2 U' R2 U' F2", "(U') R U' R' U R' U' F' U F R U R U' R' F' U' F / (U2) F' R U2 R' U R' D' R U' R' D R U' R U' R' F", "F2 r2 U' r2' U' r2 U r2' U F2", "(U') R U' R' U R U' R2' F2 R2 U' R' U' R U R' F2', (U') R U R' U' R U2 R D R' U R' U' R U R2 D' R, R' D R2 U' R' U R U' R D' R' U2 R' U R U' R'"],
	"Double Bar":["(U' D) M'R' U' r' F2 R2 U' R' F R' F2 R2 / F' R' U R U' F R U' R U' R U R' U R' / R' U D' R U' R' D R2 U' R U' R U R' U R'", "R U R' F R' F' R2 F U R U' R' F' U' R' / (U') D F U' R' F' U' F R U R' F R' F' R2 F' D'", "(U' D) R2' F2 R F' R U R2' F2 r U M R , R U' R U' R' U D R' U R D' R2 U R' U' R", "(U') R' (U' D') R2 U R' D R (U' D') R2 D R U R", "R D R2' U'D' R U2 R U2' R' U2 D R' U' R2 D' / R2 U (R U R' U' R' F R2 U' R' U' R U R' F') U' R2 / D B2 U2 R2 U' R2 U' R2 U2 R2 U B2", "R2 U R2' U' R2 B2 R' U R' B2' R U' R B2 / F' R U R' U' R' F U2 R' U D R' U' R U2 D' R / (U) R' D' R U2 R' D R2 U2' R' U' R U2' R' U' R U2' R' / (U2) R2 U' R U' R U R' D R D' R' U2 R2 D R2 U' D' R2", "R' D' R U R' D R U' R U' R' U R U R' U R U' R'", "(U') R2 U' F2 U2 R2 U F2 U2 R2 U' F2 / (U) R U R' U' R' B2' R2 U' R' U R' B2' R2 U' R' / R U2' R' U' F R' F' R r U' r' U' M' U' R U r'", "(U') D R2 U' R2 U R2 D' R2 U R2 U' R2", "(U) R U' R' D' R' D F D' R U D R U' R' F' U' R U R' / (U' D) R2 U' R' U' F' R U R' U' R' F R' U2' R U2' R / R' U2 R' U R U' D' R U2 R U R U' R2 D R", "(U') R' F R2 U' R' U' R U B R' F' R B' U R' / D R U R U' R' U D R2 U' R' U R2 U' D' R' D'", "L U' F' U2 R' F R U' L' U' L U' F L' / (U) R U R2 B2' R U' R U R2 B2' R U R U' R'"],
	"Right Bar":["x' D' R U' R' D2 R U R' D' x / (U') R' D R U' R D' R' U' R D R' U R' D' R", "(U') F U R' U' R F' D R' U' R D' U R' U R / R' U' R D R' U' R D' R' D' R U R' U D R", "(U) S R2' S' D' R2 U R2' U' R2 D / (U') R2' D R2 U' R2' U R2 D' U R2' U2 R2", "R' D' R U' R' D R U R U' R' U R U R' U R U' R'", "R' U R' U' D R2 U' R U' R' U R' U R2 U D' R2 / (U') R' D' R U R' D R2 U F U R' U' R F' U' R'", "(U) D' R' D R' D' R2 U R U M' U2 r' D / (U2) F R' F r U' r' D' r U r' D F' R F' / (U) R' D' R U R U' R' U2 R' D' r U2 r' D2 R", "R U2' r' F R' F' r U2 R U R' U2 R U2' R'", "(U') R U2' R' U2 F' R U R' U' R' F R2 U R' / (U') R U2' R' U2 R U2' F U' R' U' R U F' R' / (U) R U2' R' U2 R U2' R2' F R U R U' R' F'", "R' U' R' U2 R B R U' R' B' U' R F R F' / R U2 R' U2 R U' R' U2 R2 D r' U2 r D' R2", "R U' R D R' U2 R D' R' U2 R' U' R U2 R'", "R U2 R' U2 R U' R' U2 R2 D R' U2 R D' R2 / (U) R U' R' U R U' F R U R' U' F' R2 F R F'", "R U' R F2' R2' U R U2 R' U' R U R F2' R2' / R F R2' U R2 U' F' U' R U R2' U R U2 R2'"],
	"Front Bar":["(U') x' D R U' R' D2 R U R' D x / R' D R2 D' R' U R D R' U' R' D' R / D' L2 D R2' D' L2 D R2", "(U' D) f R' f' R2 U' R F R' F' U R2 U' R' U R / (U') R F U' D R' U R U2 R' U' R U D' R' U' R F' R'/ (U2) R' D' R U2 R' D R U2 R U' R' U R U R' U R U' R' / (U2) R U' R' U' R' F2 R U2 R U2' R' F2 U' R U R'", "R F' R U R2' U' R' F R' S R2 S' / (U') R2' U2' R2 U' D R2' U' R2 U R2' D' R2", "(U) R U' R2' F' R U R U' R' F U2 R U2' R'", "(U2) R' F R2 U' R' U R U R' F' R U' R2' F R F' / R U r' D F R' F' D' r F R F' U' R'", "(U) R U2' R' S U R' F R F' R U' R2' F R f' / R' D L' U L U' D r U2 r' F2 D2 R / (U') R' U2 R U R' U D' R U R' D R2 U2 R' U' R U' R'", "L D' L D L2' U' r' F' M' F2 R / (U') R U2' R' U R U2' R D R' U2 R D' R' U R'", "R U2' R' U2 R U' R' U2 L' U R U' L U2' R'", "(U2) D' L' U2 L U2' F L' U' L U L F' L2' U' L D / D R2' U2' R2 U D' R2' D R2 U R2' D' R2 / (U') R' U' D' R U' R' D R D R' U R D' R' U R / (U') R' U' R U' D R' U R D' F R' U R U' F'", "(U') D R' U R' D' R U2 R' D R U2 R U R' U2 R D' / (U) F R' F D' r U' r' D r U r' F' R F'", "(U2) R2 D R' U2 R D' R2' U2' R U R' U2' R U2 R'", "F U' R' F R2 U R' U R U2' R' F' R U R' F'"],
};

var ttllpi = {
	"Front Opposite":["R2 U2 R' U2 R' U' R' U' R2 U R' U' R2", "(U) R U' R' U R U2 R' U' R U R'", "R2 U' R2 U R2 U2 R2 U R2 U R2 U R2 U R2", "(U2) R2 U R2 U R2 U2 R2", "R2 U2 R2 U' R2 U' R2", "U2 R2 U R2 U' R2 U R2 U2 R2 U2 R2", "R U2 R' U' R U2 R2 U2 R U R' U R2 U R'", "R U' R' U' R U2 R' U2 R U2 R' U R U R'", "(U2) R U2 R' U' R' U2 R2 U R2 U R", "U R' U2 R U R U' R2 U2 R U2 R U R'", "R2 U2 R' U' R' U R U2 R' U' R U R U' R2", "(U) R' U' R2 U' R2 U2 R U R U2 R'"],
    "Right Opposite":["(y') R U2 R' U R2 U R2 U2 R U2 R U' R' U R'", "y' U' R2 U' R2 U R2 U2 R2 U' R2 U R2", "(y' U) R2 U2 R' U R U' R U2 R2 U' R' U' R", "(y' U2) R' U2 R U R U2 R2 U' R2 U' R'", "(U') D R2 U2 R2 U R2 U R2 D'", "(y') R2 U2 R U R U' R' U2 R U R' U' R' U R2", "y' R' U R U R' U R U2 R' U R U R' U R", "(y' U') R' U R U' R' U2 R U R' U' R", "y' U2 R2 U' R2 U' R2 U2 R2", "y' U R2 U2 R2 U R2 U' R2 U R2 U R2", "y' U2 R' U R U2 R U2 R2 U' R U R U2 R'", "(y') U' R U R2 U R2 U2 R' U' R' U2 R"],
	"Double Opposite":["U R2 U2 R2 F2 U2 R2 U' R2 U' F2 U2 R2 U' R2", "F2 U' r2 U' r2 U r2 U r2 F2", "R U2 R' U2 R' U' R2 U' R2 U2 F R U R U' R' F'", "F2 U' R2 U2 R2 U' R2 U' R2 U' F2", "R' D' U' R U' R' U2 R U2 R' U2 R U R' D U R", "R2 U R2 U2 F2 U R2 U R2 U2 F2 R2 U2 R2", "U2 R2 U2 R2 U F2 U2 R2 U' R2 U' F2", "R2 D r2 U r2 U' r2 U' r2 U D' R2", "F2 r2 U' r2 U' r2 U r2 U F2", "(U2) x R' U R U' R' U R U' R' U R U'", "U F2 U R2 U R2 U2 F2 U' R2 U2 R2 / R2 U' R2 U' R2 U' R2 B2 U2 R2 U R2 U B2", "R2 U R2 D R2 D' R2 U' R2 D R2 D'"],
	"Double Bar":["R' D' U R U' R' D R2 U' R U' R U R' U R'", "R2 U R U R' U' R' F R2 U' R' U' R U R' F U' R2 / R2 D U R2 U' R2 U R2 D' R2 U R2 U R2 U' R2", "B2 R2 U' R' U R' B2 U R' U' R' U R2 U2 R'", "R' U R' U R' U' R2 D' R U R' D2 R' U2 R D'", "R2 U R2 U' R2 B2 R' U R' B2 R U' R B2", "U R U R2 B2 R U' R U R2 B2 R U R U' R'", "R U' R U' R' U R' U R2 D' R U R' D U' R", "R' U2 R U' R2 D U R' U' R D' R2 U R2 U2 R", "B2 R2 U' R' U R' B2 U' R' U' R' U R", "R2 U R2 U' R2 D R2 U' R2 U R2 D'", "U R U R' U' R' B2 R2 U' R' U R' B2 R2 U' R'", "U' B2 R' U R' B2 R U' R B2 R2 U R2 U' R2"],
	"Right Bar":["R2 U2 F2 U' R2 U' R2 U R2 U' F2 U R2 F2", "B' U R2 U R' U R' U' B R U' R2 U' R' U R", "R U R' U2 R2 D R' U R D' R' U2 R' U R U R'", "(U') R2 U2 R2 F2 U' R2 U' R2 U F2", "R U' R F2 R2 U R U2 R' U' R U R F2 R2", "R U2 R' U2 R U' R' U2 R2 D r' U2 r D' R2", "R U' R D R' U2 R D' R' U2 R' U' R U2 R'", "U' F2 U2 R2 U R2 U R2 U2 R2 U' F2", "U' R2 D R2 U' R2 U R2 D' U R2 U2 R2", "(x') D' R U' R' D2 R U R' D'", "U R2 U R2 D U R2 U' R2 U R2 D' U2 R2", "R U2 R' U2 R U' R' U2 R2 D R' U2 R D' R2"],
	"Front Bar":["U F2 U R2 U2 R2 U' R2 U' R2 U2 F2", "U' R U2 R' U R U2 R D R' U2 R D' R' U R'", "U' R2 F2 R' U' R' U R U2 R' U' R2 F2 R' U R'", "U' R2 U2 R2 D U' R2 U' R2 U R2 D' R2", "R U R' U' R U' R' U' R U R' U' R' D' R U R' D R", "U F2 U' R2 U R2 U F2 R2 U2 R2, F2 R2 U' F2 U R2 U' R2 U R2 U F2 U2 R2", "U' R2 U2 R2 U2 R2 F2 U' R2 U R2 U F2 U2 R2", "D R2 U2 R2 U D' R2 D R2 U R2 D' R2", "(z') R' D2 R U2 R' D2 R U2", "D R2 U' R2 U R2 D' U2 R2 U R2 U' R2", "(U2) R2 D R' U2 R D' R2 U2 R U R' U2 R U2 R'"],
};

var ttllSwagrid = {
	"Front Opposite":["R' D' R U' R2 D' R U' R' D R U D R", "U' (R U R' U R U R' U) (R U' R' U) (R U R' U R U R')", "U (R U' R' U) (R U2 R' U') (R U R')", "(R U' R' U') (R U2 R' U2 R U2) (R' U R U R')", "y' R2 B2 U2 R2 U R2 U B2 R2 / y L2 F2 U2 L2 U L2 U F2 L2", "(U) S R2' S' U' R2 U' R2' U R2", "U2 (R2 U) (R2 U) (R2 U2) R2", "(U') R2' U2' R2 U' R2' U R2 U' R2' U' R2", "R2 U2 (R2 U' R2 U') R2", "U (R U' R' U) R2 U (R' U R' U') R2 U' (R' U2) R'", "(R' U2 R U2) (R U R' U2) (R U R' U') (R' U2) R", "U (R' U') (R2 U' R2 U2) (R U R U2) R'"],
    "Right Opposite":["(y') (R' U2) (R U R' U2) R2 U2 (R' U' R U') R2 U' R", "(y') (R' U R U R' U) R U2 (R' U R U R' U R) / (U' D) R2 U2 R2 U S R2 S' U R2", "(y') U' (R' U R U') R' U2 (R U R' U') R", "(y') (R' U R U) (R' U2 R U2 R' U2) (R U' R' U') R", "R2 F2 U2 (R2 U' R2 U') F2 R2", "(y') U2 (R2 U' R2 U') R2 U2 R2", "(y') U2 (R' U2) (R U R U2) (R2 U' R2 U') R'", "(y') U' (R U R U') (R' U2 R' U2) R2 U (R' U' R')", "(y') R2 U2 (R2 U R2 U) R2", "D (R U R U') R2 U2 R U2 (R U R' U') R'", "(y') R2 U2 (R U R U') R' U2 (R U R' U') R' U R2", "(y') U' R U (R2 U R2 U2) (R' U' R' U2) R"],
	"Double Opposite":["(R2 U) (R2 D R2 D') (R2 U') (R2 D R2 D')", "U2 (R' F R F') (R' F R F') (R' F R F') / U2 (x) (R' U R U') (R' U R U') (R' U R U')", "(R' U' R' U) R2 D' (R U2 R' U2) (R U' R' D) R'", "U' (R U' R' U R U') (R2 F2 R2) U' (R' U' R U) R' F2", "F2 (r2 U' r2 U') (r2 U r2 U) F2 / (y') R2 F2 U' R2 U' R2 U F2 U R2", "(U') R U' R' U R' U' F' U F R U R U' R' F' U' F", "(F2 U' r2 U') (r2 U r2 U) r2 F2 / (y') R2' U' F2 U' R2 U R2' U F2 R2", "F' (R U R' U) R' D' (R U R' D) (R U' R U2) R' F", "(z) U D R U' R2 D' R2 U R2 D R U' D' z'", "(R2 D) (R2 U') D' F2 (R2 U' R2 U') F2", "R2 D (r2 U) (r2 U' r2 U') (r2 U) D' R2 / R2 U B2 U R2 U' R2 U' B2 R2", "F2 U' R2 U2 R2 U' R2 ' R2' F2"],
	"Double Bar":["(y') R2 (r U' r') F2 (R2 U' R') F R' (F2 R2)", "(y') R2 F2 (R F' R U) R2 F2 (r U r') R2", "R2 U (R U R' U') (R' F) (R2 U' R' U') (R U R' F) (U' R2) / R2 U (R U R' U' R' F R2 U' R' U' R U R' F') U' R2", "F2 (L' U' L U) (L F' L2 U L U L' U' L F')", "R' D' (R U R') U2 (L U' (R U R') L') U2 D R U'", "(U') R' (U' D') R2 U R' D R (U' D') R2 D R U R", "(U') R' F R2 U' R' U' R U B R' F' R B' U R'", "R2 U R2 U' R2 D R2 U' R2 U R2 D'", "R2 U R2 D' F2 D R2 F2 U R2 U' F2 R2", "(R U' R' D) (R' U R U') (R' U' R D') (R2 U R U') R2", "(U D') R' F U' R U' R' U' r U r' U2 F' U' R / (U) R U R2 B2 R U' R U R2 B2 R U R U' R'", "U2 (R U2 R' U) (R U2 R' U) (R U2 R2 D') (R U2 R' D) R / (U' D) R2 U' R' U' F' R U R' U' R' F R' U2' R U2' R"],
	"Right Bar":["(x') D' (R U' R' D2) (R U R' D')", "(R U2 R' U2) (R U' R') (U2 R2) D (R' U2 R D') R2", "(R U R' U2) R2 D (R' U R D') R' U2 (R' U R U) R'", "(R U R' U') (R U' R' U') (R U R' U2) R' D' (R U2 R' D) R", "(U) S R2' S' D' R2 U R2' U' R2 D", "R U2 r' F R' F' r U2 R U R' U2 R U2 R'", "(R' U R' U') D (R2 U' R U') (R' U R' U) R2 (U D') R2", "(R U2 R' U2) (R U' R') (U2 R2) D (r' U2 r D') R2", "(R' U' R D) (R' U' R D') R' D' (R U R') U D R", "(R U' R D) (R' U2 R D') (R' U2 R' U') (R U2 R')", "U (R2 D') (R2 U) (R2 U') (R' U2 R') (r U2 r') D", "(U') R2 U2 R2 F2 U' R2 U' R2 U F2"],
	"Front Bar":["D' (r2 U R2 U') (r2 D R2) / R2 B' R D' R U' R2 U R D R' B U' R2", "U2 R2 D (R' U2 R D') R2 U2 (R U R' U2) (R U2 R')", " (U2) R' D' R U2 R' D R U2 R U' R' U R U R' U R U' R'", "(R U R' U') (R U' R' U') (R U R' U') R' D' (R U R') D R", "U' (R U R' U') R U' (R2 D') (R U' R' D) (R U2 R U') R'", "(y') R' U R' D' R U2 R' D R U2 R U R' U2 R", "(U') R U2 R' U R U2 R D R' U2 R D' R' U R'", "F (R U R' U') R' F' (R2 U2 R' U2 R U2) R'", "(U) R U2 R' S U R' F R F' R U' R2 F R f'", "f R2 S' R2 F R U' R F2 R' U R' F2 R2", "R F' R U R2' U' R' F R' S R2 S'", "(U2) R' F R2 U' R' U R U R' F' R U' R2' F R F'"],
};

var ttllLegacy = {
    "Front Opposite":["(R U' R' U' R U' R') U2 (R U' R' U' R U' R')", "U' (R U R' U R U R' U) (R U' R' U) (R U R' U R U R')", "U (R U' R' U) (R U2 R' U') (R U R')", "(R U' R' U') (R U2 R' U2 R U2) (R' U R U R')", "U' (R2 U2) (R U' R' U R' U2) R2 U (R U R')", "U2 (R U2 R' U' R' U2) (R2 U R2' U) R", "U2 (R2 U) (R2 U) (R2 U2) R2", "U (R' U' R' U) (R U2 R U2) (R2 U') (R U R)", "R2 U2 (R2 U' R2 U') R2", "U (R U' R' U) R2 U (R' U R' U') R2 U' (R' U2) R'", "(R' U2 R U2) (R U R' U2) (R U R' U') (R' U2) R", "U (R' U') (R2 U' R2 U2) (R U R U2) R'"],
    "Right Opposite":["y' (R' U2) (R U R' U2) R2 U2 (R' U' R U') R2 U' R y", "y' (R' U R U R' U) R U2 (R' U R U R' U R) y", "y' U' (R' U R U') R' U2 (R U R' U') R y", "y' (R' U R U) (R' U2 R U2 R' U2) (R U' R' U') R y", "R2 F2 U2 (R2 U' R2 U') F2 R2", "y' U2 (R2 U' R2 U') R2 U2 R2 y", "y' U2 (R' U2) (R U R U2) (R2 U' R2 U') R' y", "y' U' (R U R U') (R' U2 R' U2) R2 U (R' U' R') y", "y' R2 U2 (R2 U R2 U) R2 y", "y' U (R U R U') R2 U2 R U2 (R U R' U') R' y", "y' R2 U2 (R U R U') R' U2 (R U R' U') R' U R2 y", "y' U' R U (R2 U R2 U2) (R' U' R' U2) R y"],
	"Double Opposite":["(R2 U) (R2 D R2 D') (R2 U') (R2 D R2 D')", "U2 x (R' U R U') (R' U R U') (R' U R U') x'", "(R' U' R' U) R2 D' (R U2 R' U2) (R U' R' D) R'", "U' (R U' R' U R U') (R2 F2 R2) U' (R' U' R U) R' F2", "F2 (r2 U' r2 U') (r2 U r2 U) F2", "U (l' U2 l U2) (R U' R' U) (l' U2 l U') R U' (l' U2) x'", "(F2 U' r2 U') (r2 U r2 U) r2 F2", "F' (R U R' U) R' D' (R U R' D) (R U' R U2) R' F", "(R U' R' U') (R U' R D) (R' U' R D') (R' U R' U2) R U R'", "(R2 D) (R2 U') D' F2 (R2 U' R2 U') F2", "R2 D (r2 U) (r2 U' r2 U') (r2 U) D' R2", "F2 U' R2 U2 (R2 U' R2 U') R2 U' F2"],
	"Double Bar":["y' R2 (r U' r') F2 (R2 U' R') F R' (F2 R2) y", "y' R2 F2 R F' R U R2 F2 r U r' R2 y", "R2 y (R U R' U') (R' F) (R2 U' R' U') (R U R' F) y'", "(R U R' U') (R U' R' U') (R U R D) (R' U' R D') (R' U R' U)", "U' (R U2 R' U') (R U2 R' U') F2 (R U2 R' U2) (l' U2 l)", "R2 U (R U' R' U') (R U R D) (R' U' R D') (R' U2) (R' U2) R2", "(R2 U) (R2 D) (R2 U') (R D' R D) (R' U R U') R (U' D')", "F2 (r2 U') (r' F r' F2) R U' R'", "U R' D' (R U2 R') D R2 U2 (R' U' R U2) (R' U' R U2 R')", "(R U' R' D) (R' U R U') (R' U' R D') (R2 U R U') R2", "U' (R U2) (R' U2) (R' U' R D') (R U' R' D) (R' U2) (R U' R U) R'", "U2 (R U2 R' U) (R U2 R' U) (R U2 R2 D') (R U2 R' D) R"],
	"Right Bar":["x' D' (R U' R' D2) (R U R' D') x", "(R U2) (R' U2) (R U' R') (U2 R2) D (R' U2 R D') R2", "(R U R' U2) R2 D (R' U R D') R' U2 (R' U R U) R'", "(R U R' U') (R U' R' U') (R U R' U2) R' D' (R U2 R' D) R", "x U R U2 (r' U r U) x' U' R U2 R2", "U (R U2 R' D) (R U R U2) (R' U R' U') (R2 U2) (R' U R' D')", "(R' U R' U') D (R2 U' R U') (R' U R' U) R2 (U D') R2", "(R U2) (R' U2) (R U' R' U2) R2 D (r' U2 r) D' R2", "U' (R2 D) (R2 U') (R2 D') (R2 F2) U2 F2", "(R U' R D) (R' U2 R D') (R' U2 R' U') (R U2) R'", "U (R2 D') (R2 U) (R2 U') (R' U2 R') (r U2 r') D", "U' (R2 U2) (R2 F2) U' (R2 U') (R2 U) F2"],
	"Front Bar":["D' (r2 U R2 U') (r2 D R2)", "U2 R2 D (R' U2 R D') R2 U2 (R U R' U2) (R U2 R')", "U2 (R U R' U') R U L' (U R' U R) (U' R' U2) L U", "(R U R' U') (R U' R' U') (R U R' U') R' D' (R U R') D R", "U' (R U R' U') R U' (R2 D') (R U' R' D) (R U2 R U') R'", "D' (r U2 r') (R U2 R U) (R2 U' R2 D R2)", "U' (R U2 R' U) (R U R' U') L (U' R U) L' (U' R')", "F (R U R' U') R' F' (R2 U2 R' U2 R U2) R'", "y' (R' U2 R U2) R' U (R U2 R2 D') (r U2 r') D R2 y", "(R U2) (R' U2) (R U' R' U2) L' (U R U') L (U2 R')", "U' (R U2 R' U2) (R U R' U') R2' D (R' U R) D' R2 U", "(F U' F) (R2 u R' U) (R U' R u') R2 F2"],
};

var ttllTao = {
    "Front Opposite":["R U' R' U' R U' R' U2 R U' R' U' R U' R' / R' D' R U' R2 D' R U' R' D R U D R", "(U) R U' R' U R U2 R' U' R U R'", "(U') R2 U2 R U' R' U R' U2 R2 U R U R'", '(U2) R2 U R2 U R2 U2 R2', "R2 U2 R2 U' R2 U' R2", "R2 U2 R2 U' R' U R' U' R3 U' R' U R' / R' U2 R U2 R U R' U2 R U R' U' R' U2 R", "(U') R U R' U R U R' U R U' R' U R U R' U R U R'", "R U' R' U' R U2 R' U2 R U2 R' U R U R'", "(U2) R U2 R' U' R' U2 R2 U R2 U R", "(U) R' U' R' U R U2 R U2 R2 U' R U R", "(U) R U' R' U R2 U R' U R' U' R2 U' R' U2 R'", "(U) R' U' R2 U' R2 U2 R U R U2 R'"],
    "Right Opposite":["y' R' U2 R U R' U2 R2 U2 R' U' R U' R2 U' R y / y' R2 U2 R U' R2 U R U R' U2 R2 U2 R' U R2 y", "(y' U') R' U R U' R' U2 R U R' U' R y", "R2 F2 U2 R2 U' R2 U' F2 R2 / (y' U) R2 U2 R' U R U' R U2 R2 U' R' U' R y", "R U2 R' U2 R U2 R2 F' R U R U' R' F / (y' U2) R' U2 R U R U2 R2 U' R2 U' R' y", "y' R2 U2 R2 U R2 U R2 y / (U') D R2 U2 R2 U R2 U R2 D'", "y' R2 U2 R U R U' R' U2 R U R' U' R' U R2 y", "y' R' U R U R' U R U2 R' U R U R' U R y / R U' R D R' U R U D' R D R' U' R D' R", "(y' U') R2 U' R2 U R2 U2 R2 U' R2 U R2 y / (U') R U R' U' R U' R D R' U2 R D' R' U R' U R U' R' / y' (R' U R U) (R' U2 R U2 R' U2) (R U' R' U') R", "(y' U2) R2 U' R2 U' R2 U2 R2 y", "(y' U') R U R U' R' U2 R' U2 R2 U R' U' R' y", "(y' U) R U R U' R2 U2 R U2 R U R' U' R'y", "(y' U') R U R2 U R2 U2 R' U' R' U2 R y"],
    "Double Opposite":["R2 U R2 D R2 D' R2 U' R2 D R2 D' / F R U' R2 D R U' R' D' R U R U R' F'", "R U2 R' U2 R' U' R2 U' R2 U2 F R U R U' R' F' / R' U' R' U R2 D' R U2 R' U2 R U' R' D R'", "F2 r2 U' r2 U' r2 U r2 U F2", "F2 U' r2 U' r2 U r2 U r2 F2", "R U' R' U' R U' R D R' U' R D' R' U R' U2 R U R'", "R2 D r2 U r2 U' r2 U' r2 U D' R2 / F2 U R2 U R2 U R2 U2 R2 U F2", "(U2) x R' U R U' R' U R U' R' U R U' x'", "(U') R U' R' U R U' R2 F2 R2 U' R' U' R U R' F2 / (U') R U R' U' R U2 R D R' U R' U' R U R2 D' R", "(U) l' U2 l U2 R U' R' U l' U2 l U' R U' l' U2 x' / (U') R U2 R' U2 R U2 R' U' R U' R D R' U R D' R' U R'", "F' R U R' U R' D' R U R' D R U' R U2 R' F / (U') R2 U' F2 U' F2 R2 U2 R2 D R2 D'", "R2 D R2 U' D' F2 R2 U' R2 U' F2 / (U2) R U' R' U2 R U' R D R' U R D' R' U R' U R U R'", "F2 U' R2 U2 R2 U' R2 U' R2 U' F2"],
    "Front Bar":["R' D R2 D' R' U R D R' U' R' D' R / z' R' D2 R U2 R' D2 R U2 z / D' r2 U R2 U' r2 D R2", "(y' U') F R2 U' R' U2 R' U2 R2 U R' U' R' U' R U R' F' y / R2 U R U R U' R' U' R U' R' U' D R' U R U D' R", "(U') R U R' U' R U' R2 D' R U' R' D R U2 R U' R' / F2 R U' l D2 l' U R' U2 R2 F2 R2 U2 F2", "(U') R U2 R' U R U2 R D R' U2 R D' R' U R'", "D R2' U' R2 U R2' D' U2' R2 U R2' U' R2/z U R U' R U' R2 D R U' R' D' R U' R' U' R U' R U z'/ y' R' U2 R U2 R' U R U2 R2 D' r U2 r' D R2 y", "(U') R2 U2 R' U x U' r' U' r U2 R' U' x' / (U') R2 D R' U' R D' R2 U R U' R' U2 R U2 R'", "(U2) R2 D R' U2 R D' R2 U2 R U R' U2 R U2 R'", "R U R' U' R U' R' U' R U R' U' R' D' R U R' D R", "D' r U2 r' R U2 R U R2 U' R2 D R2 / (U') D R' U R' D' R U2 R' D R U2 R U R' U2 R D'", "F R U R' U' R' F' R2 U2 R' U2 R U2 R' / y' R' U R' D' R U2 R' D R U2 R U R' U2 R y", "R U2 R' U2 R U' R' U2 L' U R U' L U2 R' / D R U' R U2 R2 U R U' R U2 R' U' R' D' R U2 R'", "F U' F R2 u R' U R U' R u' R2 F2 / (U') R2 U' D R2 U' R U' R U R' U R2 U D' R U' R"],
    "Right Bar":["x' D' R U' R' D2 R U R' D' x", "R U R' U2 R2 D R' U R D' R' U2 R' U R U R'", "x U R U2 r' U r U x' U' R U2 R2 / D' R2 U R D R' D' R U' R' U R' D R2", "R' U R' U' D R2 U' R U' R' U R' U R2 U D' R2", "(U) R U R' U2 R' D' R U R' D R2 U R' U R U' R' / (U') R2 D R2 U' R2 D' R2 F2 U2 F2", "D R' U2 R U' R' U2 R' D' R U2 R' D R U' R D' / U R2 D' R2 U R2 U' R' U2 R' r U2 r' D", "R U2 R' U2 R U' R' U2 R2 D R' U2 R D' R2", "R U R' U' R U' R' U' R U R' U2 R' D' R U2 R' D R / z R U' R2 D R D' R' D R' U R' D' R D R' D' z'", "R U2 L' U R' U' L U2 R U R' U2 R U2 R' / (U) R U2 R' D R U R U2 R' U R' U' R2 U2 R' U R' D'/ y r' F2 r U2 r' F r U2 R U' r' F R' F2 r y'", "R U2 R' U2 R U' R' U2 R2 D r' U2 r D' R2", "R U' R D R' U2 R D' R' U2 R' U' R U2 R'", "(U') R2 U2 R2 F2 U' R2 U' R2 U F2"],
    "Double Bar":["y F2 R2 F2 R' U' R F2 R' U R' U' F2 / y' R2 r U' r' F2 R2 U' R' F R' F2 R2", "y F2 R U R' U' R' F R2 U' R' U' R U R' F", "(U') R U2 R' U' R U2 R' U' F2 R U2 R' U2 l' U2 l", "R2 U R2 D R2 U' R D' R D R' U R U' R D'", "(U) R' D' R U2 R' D R2 U2 R' U' R U2 R' U' R U2 R'", "R' D' R U R' D R U2 R U' R' U R U' R' U2 R U2 R'", "y F2' U R U' R F2' R' U R F2' R2' F2' / y' R2 F2 R F' R U R2 F2 r U r' R2 / R U' R U' R' U R' U R2 D' R U R' U' D R", "R U R' U' R U' R' U' R U R D R' U' R D' R' U R'", "R' U2 R2 F R F' R U' R' F' U F R U' R / R2 U R U' R' U' R U R D R' U' R D' R' U2 R' U2 R2", "F2 r2 U' r' F r' F2 R U' R'", "(U') R2 U2 R2 U' R' U' l D2 l' U R' U' R2 F2 / R U' R' D R' U R U' R' U' R D' R2 U R U' R2", "R' U2 R' U R U' D' R U2 R U R U' R2 D R / (U2) R U2 R' U R U2 R' U R U2 R2 D' R U2 R' D R"],
};

var tsle = {
    "UN3":["U (R U' R') U' (R U' R') U (R U' R')"],
	"UN2":["R U' R'", "U' (R U2) (R' U2) (R U2) R'", "R2 D (R' U' R D') R2", "(R U' R' U) (R' U' R U' R' U2 R)", "(R U R' U2) (R U' R' U') R U R'", "(R U R' U') (R U' R')"],
	"UN1":["U (R U' R' U) (R U2 R')", "(U2 R U2 R') (U R U2 R')", "U' (R U' R' U) (R U R' U') (R U' R')", "(R U' R' U') (R U2 R' U' R U' R')", "(R U R' U2) (R U2 R' U) (R U' R')", "U' R U' (R' U R U') R'", "U' (R U R' U2) (R U2 R')", "U' L' (U R U' R') L / U (R U2 R') U' (R U2 R' U' R U' R')", "(R U2 R') U (R U' R') U (R U' R')", "U (R U2 R')", "U' (R U2 R' U) (R U' R')", "U' (R U R' U') R U R'"],
	"UN0":["(R U' R' U') (R U R' U) (R U2 R')", "(R U' R' U) (R U R' U R U2 R')", "R U R D (R' U2 R D') R2", "U (R U' R' U) (R U' R' U) (R U2 R')", "U R U' R' U' R U' R' U' R U R' U", "U2 (R U R' U') (R U R' U2) R U R'", "(R U' R' U) R U2 (R' U' R U') R'", "(R U R' U') (R U R' U') R U' R'"],
	"UCw4":["U (R U' R') U2 (R U R')"],
	"UCw3":["U' R U R' U R U' R'", "U' L U' R U R' L' / R U R' U R U R' U R U' R' U' R U2 R'", "U R U' R' U' R U R' U R U' R'", "U2 R U R' U' R U' R' U2 R U' R'", "R' D' r U2 r' D R", "R' U2 R U R' U R U' R U R'"],
	"UCw2":["R U' R' U' R U R' U2 R U R'", "U R U2 R' U2 R U R' U2 R U R'", "R U R' U R U' R' U' R U' R'", "R U' R' U R U2 R' U' R U R' U R U R'", "U2 R U' R' U2 R U R' U R U' R'", "R U R' U2 R U R' U R U' R'", "U2 F' R U R' U' R' F R / R U' R U R' U R U2 R' U R'", "U2 R U R'", "U R U' R' U R U' R' U2 R U R'", "U' R U R' U' R U' R' U R U R'", "R U2 R' U' R U R' U2 R U' R'", "R U' R' U2 R U R' U2 R U R'"],
	"UCw1":["R U' R' U R U R' U2 R U R'", "U' R U R' U R U2 R' U' R U2 R'", "U R U R' U' R U R' U2 R U' R'", "U R U R D R' U2 R D' R' U' R'", "U R' U' R U' R' U2 R U' R U R'", "R U2 R' U' R U R' U' R U2 R'", "R U R' U R U R'", "U R U R' U' R U R' U' R U2 R'"],
	"UCcw3":["R U R' U' R U2 R' U' R U2 R'"],
	"UCcw2":["R U2 R' U R U R' U R U' R'", "U' R U' R' U2 R U2 R'", "R U2 R' U R U2 R' U R U' R'", "U R U' R' U R U R' U2 R U' R'", "U' R U R' U2 R U' R' U R U2 R'", "R U' R' U' R U' R' U2 R U' R'"],
	"UCcw1":["U R U2 R' U' R U' R' U' R U2 R'", "R U R' U R U' R' U R U R'", "R U' R' U2 R U' R' U2 R U' R'", "U' R U2 R' U' R U2 R' U2 R U R'", "U R U R' U2 R U' R'", "U R' U2 R U R' U R2 U' R'", "U2 R U' R' U R U R'", "U' R U' R' U R U2 R' U' R U2 R'", "R U' R' U' R U' R' U' R U2 R'", "R U2 R' U' R U2 R'", "R U2 R D R' U R D' R2 / R U' R' U R U' R' U R U R' U R U' R'", "R U' R' U R U' R' U2 R U' R'"],
	"UCcw0":["U R U R' U R U2 R' U R U' R'", "U R U R' U' R U2 R'", "R U2 R' U2 R U' R'", "U2 R U2 R' U' R U R' U' R U R' / U R U R D R' U R D' R2", "U R U' R' U R U R' U' R U2 R'", "U' R U2 R' U' R U' R' U R U R'", "U2 R' U2 R U R' U R U' R U2 R'", "U2 R U R' U' R U2 R' U' R U' R'"],
	"SCw":["(R U R' U') (R U R' U) (R U' R')", "(R U2) (R' U2) (R U R' U) (R U' R')", "(R U2 R') U (R U2 R' U2) (R U R')", "U' (R U2 R' U) (R U R')", "U2 (R U' R' U') (R U R' U') (R U2 R')", "(R U2 R') U' (R U R' U R U R')", "(R U R' U') (R U R' U) (R U2 R' U') (R U2 R')", "U (R U R') U2 (R U R')"],
	"SCcw":["(R U' R' U) (R U R' U) (R U' R')", "U2 (R U' R' U') (R U2 R')", "(R U R' U') (R U' R' U2) (R U2 R')", "U' (R U' R') U2 (R U' R')", "(R U' R' U) (R U2 R' U) (R U' R')", "U (R U R' U') R U2 (R' U' R U') R' U (R U R')", "(R U2) (R' U R U R' U) R U2 (R' U' R U' R')", "U2 (R U' R' U) (R U R' U') (R U R')"],
};

var tsleTao = {
	"Full":["U R U' R' U' R U' R' U R U' R'", "R U' R'", "U' R U2 R' U2 R U2 R'", "R2 D R' U' R D' R2", "R U' R' U R' U' R U' R' U2 R", "R U R' U2 R U' R' U' R U R'", "R U R' U' R U' R'", "U R U' R' U R U2 R'", "U2 R U2 R' U R U2 R'", "U' R U' R' U R U R' U' R U' R'", "R U' R' U' R U2 R' U' R U' R'", "R U R' U2 R U2 R' U R U' R'", "U' R U' R' U R U' R'", "U' R U R' U2 R U2 R'", "U R U2 R' U' R U2 R' U' R U' R'", "R U2 R' U R U' R' U R U' R'", "U R U2 R'", "U' R U2 R' U R U' R'", "U' R U R' U' R U R'", "R U' R' U' R U R' U R U2 R'", "R U' R' U R U R' U R U2 R'", "U' R U' R' U' R U' R' U R U R'", "U R U' R' U R U' R' U R U2 R'", "U2 R U R' U' R U R' U2 R U R'", "U2 R U R' U' R U R' U2 R U R'", "R U' R' U R U2 R' U' R U' R'", "R U R' U' R U R' U' R U' R'", "U R U' R' U2 R U R'", "U' R U R' U R U' R'", "R U R' U R U R' U R U' R' U' R U2 R'", "U R U' R' U' R U R' U R U' R'", "U2 R U R' U' R U' R' U2 R U' R'", "R' U2 R U R' U R U' R U R'", "U2 R U2 R' U' R U' R' U R U' R'", "R U' R' U' R U R' U2 R U R'", "U R U2 R' U2 R U R' U2 R U R'", "R U R' U' R U R' U R U R'", "R U' R' U R U2 R' U' R U R' U R U R'", "U2 R U' R' U2 R U R' U R U' R'", "R U R' U2 R U R' U R U' R'", "R U' R U R' U R U2 R' U R'", "U2 R U R'", "U R U' R' U R U' R' U2 R U R'", "U' R U R' U' R U' R' U R U R'", "R U2 R' U' R U R' U2 R U' R'", "R U' R' U2 R U R' U2 R U R'", "R U' R' U R U R' U2 R U R'", "R U2 R' U' R U' R' U R U2 R'", "U R U R' U' R U R' U2 R U' R'", "U R U R D R' U2 R D' R' U' R'", "U R' U' R U' R' U2 R U' R U R'", "R U2 R' U' R U R' U' R U2 R'", "R U R' U R U R'", "U R U R' U' R U R' U' R U2 R'", "U' R U R' U R U R' U' R U' R'", "R U2 R' U R U R' U R U' R'", "U' R U' R' U2 R U2 R'", "R U2 R' U R U2 R' U R U' R'", "U R U' R' U R U R' U2 R U' R'", "U' R U R' U2 R U' R' U R U2 R'", "R U' R' U' R U' R' U2 R U' R'", "U R U2 R' U' R U' R' U' R U2 R'", "R U R' U R U' R' U R U R'", "R U' R' U2 R U' R' U2 R U' R'", "U' R U2 R' U' R U2 R' U2 R U R'", "U R U R' U2 R U' R'", "U R' U2 R U R' U R2 U' R'", "U2 R U' R' U R U R'", "U' R U' R' U R U2 R' U' R U2 R'", "R U' R' U' R U' R' U' R U2 R'", "R U2 R' U' R U2 R'", "R U' R' U R U' R' U R U R' U R U' R'", "R U' R' U R U' R' U2 R U' R'", "U R U R' U R U2 R' U R U' R'", "U R U R' U' R U2 R'", "R U2 R' U2 R U' R'", "U U R U U R' U' R U R' U' R U R'", "U R U' R' U R U R' U' R U2 R'", "U' R U2 R' U' R U' R' U R U R'", "U2 R' U2 R U R' U R U' R U2 R'", "U2 R U R' U' R U2 R' U' R U' R'", "R U R' U' R U R' U R U' R'", "R U2 R' U2 R U R' U R U' R'", "R U2 R' U R U2 R' U2 R U R'", "U' R U2 R' U R U R'", "U2 R U' R' U' R U R' U' R U2 R'", "R U2 R' U' R U R' U R U R'", "U R U R' U' R U R' U R U U R' U' R U2 R'", "R U' R' U R U R' U R U' R'", "U2 R U' R' U' R U2 R'", "R U R' U' R U' R' U2 R U2 R'", "U' R U' R' U2 R U' R'", "U' R U' R' U R U2 R' U R U' R'", "U R U R' U' R U U R' U' R U' R' U R U R'", "R U2 R' U R U R' U R U2 R' U' R U' R'"], 
}

var ols = {
    "1": [ "U2 R' D' r U2 r' D R / R U' R' U L' U2 R U' R' U2 L", "L' U2 L R U' R' U L' U L / R U R' U' R U R' U R U2 R'", "R U' R' F' R U2 R' U2 R' F R / R U' L' U2 L U2 R' U2 L' U2 L / R U' L' U' L U2 R' U2 L' U L", "U2 L R U' R' U L'", "R U R'", "R U' L' U2 L U L' U L R' / R U R' U R' U2 R U R' U R", "R U R D R' U R D' R' U' R' / R U' R2 D' R U' R' D R2 U' R' / R U' R' U' R2 D R' U' R D' R2", "U L' R U R' U R U' R' U2 L / R U2 R2 D' R U R' D R2 U2 R'", "R U' R D R' U2 R D' R2'", "R U2 R' U R U2 R'", "R U' R' U R' D' R U2 R' D R2 U' R'", "U2 R U' R2 D' R U' R' D R", "R U2 R' U R U' R' U R U' R' U R U2 R'/ R U' R' U' R U R' U' R U R' U' R U' R' / U' L' U R2 U' L U R' U R'", "R U' R' U' R U R' U' R U' R'", "R U' R2 U' R2 U' R2 U2 R", "L' U2 L U L' U L R U2 R'", "R U' R' U' R U' R'", "R U2 R' U' L' U R U' R' L", "R U2 R' U2 R' D' R U2 R' D R2 U' R' / R U' R' L' U R U' R' L U' R U' R'", "U2 L R U' R2 U L' U' R / U2 L R U' R' U2 L' U L U2 L' / U2 R U R' U2 R U R' U2 R U2 R'", "R U2 R' U R U' R' U R U2 R'", "R U R2 U2 R U R' U R", "R U2 R D R' U' R D' R2'", "R U' R' U' R U' R2 U' R U' R' U2 R", "R U R' U R' U' R U' R' U2 R", "U' R U R D R' U R D' R2'", "R U' R' U2 L' U R U' R' L" ],
    "2": [ "L' U2 R U' R' U2 L U R U R' / U' R U2 R D R' U2 R D' R' U' R'", "U' R U R' U R U' R' U' R U' R'", "R' U' R U' R' U2 R2 U R' U R U' R'", "U R U2 R2 U' R U' R' U2 R2 U2 R' / U R' U2 R2 U R2 U R U2 R U' R'", "U2 R' U' R U' R U R2 U R / R U2 R' U2 R U' R' U' R U2 R'", "R L U L' U L U2 L' U' R' / U2 R2 D R' U' R D' R2 U' R U R' / R U2 R U R' U R U2 R' U R'", "U R U R2 D' R U2 R' D R", "U R U' R' U R U2 R' U2 R U R'", "U' R U2 R' U' R2 U R' U R U2 R2 / U R U R' U R U2 R' U R U' R' U' R U' R'", "U R U R' U R U2 R' U R U R'", "R' D' R U R' D R2 U R'", "R U R2 U' R2 U' R2 U2 R2 U R'", "U2 R U2 R' U' R U2 R' U2 R U R'", "U' R U R' U R U R'", "U R U' R' U2 R U R' U' R U R'", "U' R U R' U R U2 R' U R U2 R'", "U2 R U' R' U' R U R'", "U' R U2 R D R' U R D' R2 / U' R U' R2 D' R U R' D R / L U' R' U L' U' R2 U' R'", "R U2 R' L U' R U L' U' R'", "U' L' U2 L U L' U R L U' R'", "U R U R' U' R U R' U2 R U R'", "R U' R' U R U R' U' R U2 R'", "R2 D R' U R D' R' U R'", "R' U2 R U2 R U R' U' R' U R2 U' R' / R U R' U' R U2 R' U R U' R' U2 R U' R'", "U R U R U' L' U R2 U' L / U2 R' U' R U' R U R' U' R' U2 R", "U R' U2 R U R' U R U' R U2 R' / U' L' U2 L U L' U L U R U2 R'", "R U2 R' U2 R U' R' U2 R U' R'" ],
    "3": [ "U' L U' R U2 L' U2 R' U2 L U' L'", "R' U2 R U' R U2 R' U2 R' U' R2 U' R'", "U2 R U2 R' U R U2 R' U R U' R'", "R U R' U2 R U' R' U R U R'U' R U R'", "R U' R' U R U2 R' U R U2 R'", "R' U' R' U' R U R U R2 U R'", "R U2 L' U R' U' L U R U2 R'/R2 D R' U R D' R2'", "R U R' U2 R U R' U2 R U R'", "U2 R U R' U R U' R' U R U R'", "U R' U2 R2 U R U' R' U R2 U' R' U2 R", "R U2 R' U2 R U' R' U R U2 R' U2 R U R'", "U R U2 R' U2 R U R' U2 R U' R'", "R2 U' R' U2 R2 U R' U2 R2 U' R' U2 R", "U R U2 L U' R' U L' R U' R'", "R U' R2 U2 R U R' U R2 U' R'", "R U' R' U R U R'", "R2 U2 R2 U' R2 U' R2 U' R U R'", "R2 U' R' U2 R2 U R' U2 R U R", "U' R2 U R' U R U2 R2", "U' R U R' U R U2 R' U R U' R'", "U' R U' R' U R2 U R' U R U2 R2", "R U' R' U R U' R' U' R U' R'", "U R U2 R' U2 R U R' U' R U2 R'", "R U2 L' U R' U' L R U' R'", "R U2 R' U' R U' R' U' R U R'", "R2 D R' U2 R D' R' U' R'", "U2 L U' R U R' L' U' R U R'" ],
    "4": [ "R U' R' D R D R' U R D' R' D' / U R' U2 R U R' U R2 U2 R' U' R U2 R' / R U2 R' U2 R U2 R' U' R U' R' U R U2 R'", "U' R U R' U R2 U2 R' U' R U' R' U' R' / U' R U' R' U' R' U' R U' R' U2 R2 U R' / R U R' U' R U' R' U R U R' U2 R U R'", "U R U' R' U2 R U2 L U' R' U L' / U R U2 R' U' R U R' U' R U R' U R U' R'", "R' D' R U2 R' D R2 U R' / U2 R U R' U' R U R' U' R U R' U R U' R'", "R' U2 R2 U R' U' R' U2 R", "U' R U2 R' U R' U2 R2 U R2 U R U' / R U R' U2 R U R' U2 R U R' U2 R U' R'", "D R2 U2 R' U R U R2 D' / U' R2 U R2 U R2 U2 R' U R' / R U' R' U2 R U R' U' R U' R' U2 R U2 R'", "R D' R2 U2 R2 U' R2 U' R2 U' D R' / R' U2 R2 U R' L U2 R' U' R U2 L' / R U' R' U R U' R' U' R U' R' U R U2 R'", "R2 U2 R' U' R U' R2 U R U2 R'", "R' U2 R2 U R2 U R", "R2 D R' U2 R D' R' U R' / R U R' U2 R U R' U2 R U R' U' R U2 R'", "U R U' R' U2 R U2 R' U2 R U R'", "U R U' R' L U' R U R' U' R U R' L' / R U' R' U' R U2 R' U' R U R' U R U R'", "R2 U2 R U' R' U R' U2 R' U' R' / R U' R' U2 R U R' U' R U' R' U R U' R'", "R U' R' U R U' R' U2 R U' R'", "R' U2 R2 U R D' R U R' D R2 / U2 R' U2 R U R' U R U' R U R' U2 R U' R' / U2 R U2 R' U R U' R U R' U R U2 R' U' R'", "R2 U2 R' U' R U' R' U' R' / R U' R' U R U' R' U' R U2 R'", "R' U2 R2 U R2 U R2 U2 R' U' R U' R' / U R U R' U2 R U2 R' U2 R U2 R' U' R U2 R'", "U R U R' U2 R2 D R' U2 R D' R' U R' / U' R U R' U R U2 R' U2 R U2 R' U2 R U' R'", "R' D' R U2 R' D R2 U2 R' U R U2 R' / R U R' U2 R U2 R' U R U2 R' U' R U2 R'", "R' U2 R2 U R2 U' R U R' U R / R U R' U R U' R' U' R U R' U R U R'", "U R U' R' U' R U R' U' R U R'", "U2 R U2 R' U' R U R' U' R U R'", "R U2 R' U2 R U2 R' U2 R U' R'", "U2 R' U' R U' R' U2 R2 U R'", "U R U' R' U' R L' U R' U' R L U R' / U' R' U' R U' R' U2 R U' R U2 R' U' R U R'", "R U2 R' U2 R U2 R' U' R U2 R'" ],
    "5": ["U L' U2 R U R' U2 L / U' L' U2 R U' R' U2 L / y' U r D r' U' r D' r' / y2 L F L' U' L U L F' L2 ","U R U' R' ","R' F R U R U' R' F' / U' L U' R U L' U R' ","U R2 D R' U' R D' R2 ","U R U' R' U R' U' R U' R' U2 R / U R U' R' U2 R U2 R' U' R U' R' ","R U' R' U2 R U' R' U2 R U R' ","U R U R' U' R U' R' / R' U' R U R U' R' U' R' U R ","U2 R U' R' U R U2 R' ","U2 F' R U2 R' U2 R' F R / U L' U2 R U L U' L' U R' U2 L ","R' F R2 U R' U' R U R' U' F' / U R U R2 U' R2 U' R2 U2 R / U2 F2 L' U L U L' U' L F2 ","U2 R' U' R2 U' R2 U2 R ","U R U2 L U L' R' U2 L U L' / R' F2 R F2 U L' U L ","U2 R U2 R2 U' R U' R' U2 R / U' F2 L' U L U' L' U' L F2 ","U2 R2 D R' U2 R D' R2 / U2 L' U R U' L U2 R' ","L' U R U' R' L / r' F R F' M' / L' U R U' M' x' ","U2 L' R U R' U' L R U2 R' / U2 M x U R' U' L R U2 R' / U2 R U' R' U' R' F R U R U' R' F' / U R' D' R U R' D R2 U2' R' ","U2 R U2 R' ","R' F' R U2 R U2 R' F / U L' U2 R U' R' U2 L U R U' R' ","R' F2 R2 U' R' U' R U R' F2 / U2 L' U R U' R' L U' R U' R' ","U R U' R' U' R U R' U R U2 R' / U L' U2 L R U R' U L' U L ","U2 R U' R D R' U' R D' R2 / U R U' R2 U2 R U R' U R / U2 R2 D R' U' R D' R' U' R' ","U R U R D R' U2 R D' R2 / U R2 D R' U R D' R' U2 R' ","R2 U R' U R' U' R U R U2 R2 / U2 R' U L U' R2 U L' U R' / U2 R U' R' U L' U R U' R' L U' R U' R' / U2 R U R' U' R U R D R' U R D' R2' ","U2 R U' R' U R U' R' U R U2 R' ","U2 R U2 R2 U2 R U R' U R / U2 R U' R' U R U' R D R' U' R D' R2 ","U R U' R2 U' R U' R' U2 R / U R U R' U F2 L' U L U' L' U' L F2 ","U R U R' U' R U R' U' R U' R' "],
    "6": [ "R L U2 L' U2 R' U2 L U2 L'", "U' R2 U2 R2 U' R2 U' R' U' R' / R D L U2 L' U L U L' D' R'", "R U' R' U' R U2 R' L' U R U' R' L", "D R2 U' R' U' R U2 R2 D'", "U L U' R U' L' U' L U' L' U R'", "R' D' R U2 R' D R U R U' R'", "L U' R U L' U R' U' R U2 R' / U R U R' U R U' R' U' R U2 R'", "R U R' L' U R U' R' U R U' R' L", "R U R' U R' D' R U R' D R2 U' R'", "U R U2 R2 D' R U2 R' D R2 U R'", "U' R U2 R' U' R U' R' U R U2 R'", "R U' R' U' R U2 R' U R U' R'", "L' U L U' R L' U' R' L U2 L' U2 L", "U' R U2 R2 D' R U2 R' D R2 U' R'", "U' R U2 R2 D' R U' R' D R2 U2 R'", "R U' R' U' R U2 R' U2 R U2 R'", "U2 R L U2 R' U2 R U2 R' L' / R' D' R U2 R' D R U2 R U2 R'", "U' R U2 R' L' U2 R U' R' U2 L / U R U R' U R U' R' U2 R U' R'", "U' R U2 R' U' R U2 R'", "R U R' U R U' R' U R U' R'", "R U R' U R U' R' L' U R U' R' L", "U' R U2 R' L U' R U L' U R'", "U2 R U' R' U2 R U R' U' R U2 R'", "U' R U2 R' U L' U R U' R' L", "U2 R2 U' L' U R' U' R' U R U' R' L / R U' R' U2 R U' R' U R U' R' U R U R'", "U' R U2 R' U2 R U' R'", "R U R' U R U' R' U2 R U2 R'" ],
    "7": [ "U' R U R2 D' R U2 R' D R2 U' R'", "U R2 U R U R' U' R' U' R2/ U2 R U R' U2 R U' R' U' R U R'", "L U' R U R' U' R U L' U R' / U' R U R' U2 R2 D R' U' R D' R2", "R' D' R U R' D R U R U' R'", "U' R U R2 D' R U' R' D R2 U2 R' / U2 R U' R U R' U R U2 R' U R'", "R U2 R' U' R U2 R' U' R U R'", "U' R U R' U' R U' R' U R U2 R'", "U L R U' R' U L' R U' R' / U2 F R U R' U' R' F' R2 U' R'", "U' R U R' U L' U R U' R' L / U R U R2 F2 R U2 R U2 R' F2 / U R U' R2 F' R U R U' R' F", "U' R U R' U' F' R U2 R' U2 R' F R / R U' R' U2 R U R' U' R U2 R' U2 R U R'", "U' R U R' U2 R U R' U' R U' R'", "U' R U R' U2 R U' R'", "R U' R' U2 R U2 R' U' R U R'", "L' U' L U R U2 L' U2 R' L / U' R U R' L' U2 R U' R' U2 L", "U2 R U' R' U2 R U' R' U2 R U' R'", "U2 R2 U R2 U R2 U2 R' U' R' / U R2 U2 R2 U' R2 U' R2 U' R U' R' / R U' R' U' R U2 R' U' R U R' U2 R U' R'", "U' R' U' R U' R' U2 R U' R U R'", "U R U R' U R U2 R' U' R U2 R'", "U R2 U2 R2 U' R2 U' R' U2 R' / R U' L U2 L' U' L U' R' L' / R U R U2 R' U' R U' R' U2 R'", "U' R2 U2 R' U' R U' R2 U2 R U' R' / R' U' R U' R' U R U' R' U2 R2 U R' / R U R' U' R U' R' U' R U R' U' R U2 R'", "U' R U R' U2 R U' R2 U' R U' R' U2 R / R U2 R D R' U2 R D' R2 U2 R U' R'", "R' D' R U R' D R U2 R U2 R' / U R U2 R' U2 R2 U R' U R U2 R2 / R U2 R' U2 R U' R' U2 R U2 R' U2 R U2 R'", "U D R2 U R2 U2 R U2 R U' R2 D' / U2 R2 U R2 U R2 U2 R2 U R U2 R' / R U R' U' R U R' U' R U2 R' U' R U R'", "U' L U L' U L U2 R L' U' R' / U R U R' U R U2 R' U2 R U' R'", "U' R2 U2 R' U' R U' R2 U' R U2 R' / R U' R' U2 R U2 R' U' R U' R' U' R U' R'", "U' R U R' U' R U2 R'", "U R U2 R' U' R U' R' U R U R'" ],
    "8": [ "R' D' R U' R' D R U R U' R'", "R U2 R' U R U R' U2 R U2 R'", "U' R2 U R' U R2 U' R' U R' U2 R2", "L U L' U L U R U R' L'", "U2 R U R2 D R' U2 R D' R' U2 R2", "R U' R U2 R2 U' R2 U' R2", "R U2 R' U R U R' U R U' R'", "U R U2 R' D R' U R U2 R' U R D'", "U2 R U R2 D R' U R D' R' U' R2", "U R U2 R2 D R' U R D' R' U' R2", "U R U2 R D R' U' R D' R' U R'", "U2 R U R' U' R U2 R' U R U R'", "R U' R' U R' U' R2 U' R2 U2 R2 U' R'", "U R U2 R2 D R' U2 R D' R' U2 R2", "R U2 R' U2 L' U R U' L U' R'", "U' R2 U2 R U' R' U R' U2 R2", "R L' U' L U' L' U2 L U' R'", "U R' U2 R' U R U' R U2 R2 U' R'", "R U R' U2 R U' R' U2 R U2 R'", "U' R U' R U2 R U' R' U R' U2 R2", "R U R U R' U R U L' U R2 U' L / U2 R U R' U' R U2 R' U R U' R' U' R U' R'", "R U R U' L' U R2 U' L U2 R U R'", "U R U' R' U R2 U R' U R' U' R2 U' R2", "R U R' U2 R U' R' L' U R U' R' L", "R U2 R' U' L U L' U L U2 R U' R' U L'", "R U R' U2 R U' R' U R U' R'", "R U R' U L' U R U' R' L U R U' R'" ],
    "9": [ "R2 U R' U R U2 R' U' R' / R U' R' U R U2 R' U R U R'", "R U R' U R U2 R' U2 R U R'", "U2 R U R' U' R U' R' U2 R U' R'", "L U' R' U L' U' R U' R U R'", "U2 R U2 R' U' R U' R' U R U' R'", "U R U' R' U' R U' R' U R U' R'", "R' U' R U' R' U2 R U' R U' R'", "U2 R2 U2 R' U' R U' R2 / R U' R' U' R U R' U2 R U R'", "R U R' U R U2 L U' R' U L'", "R U' R U' L' U R2 U' L", "U R2 U2 R' U' R U' R' U R'", "U' R U R' U' R2 U2 R' U' R U' R2", "R U' R' U R U2 R' U R U' R' U' R U' R' / U2 R2 U2 R' U2 L' U R U' L R2 /R' U2 R U R' U R2 U R' U2 R U2 R'", "R' U' R U' R' U2 R U' R U R' U' R U' R'", "U' R' U' R U' R' U2 R U R U2 R'", "R U R' U2 R U R' U' R U R'", "U' R U' R' U2 R2 U2 R' U' R U' R' U R'", "R U2 R' U2 R U R' U R U R'", "U L' U' L U' L' R U' R' U2 L", "R2 U R' U R U2 R2 U R U2 R'", "R' U' R U' R' U2 R2 U2 R'", "U2 R' U2 R U R' U R2 U R'", "U' R' U' R U' R' U2 R2 U' R'", "U2 R U' R' U R2 U2 R' U' R U' R2", "U R' U2 R U R' U R2 U R' U R U R'", "R' U' R U' R' U R2 U' R2 U2 R", "U' R U2 R' U' R2 U2 R' U' R U' R2" ],
    "10": [ "R U R' U R U2 R U R' U R U2 R2 / R U R' U R U R' U2 R U' R' U R U R'", "U R U' R2 D' R U R' D R2 U' R' / R U R' U2 R U2 R U R' U R U2 R2 / R U' R' U R U R' U2 R U R' U2 R U R'", "U2 R U R' U' R U2 R' U' R U2 R'", "U R U2 R' U2 R U2 R2 U' R U' R' U2 R", "R U' R' U R2 D R' U R D' R2", "R U2 R' U2 R2 D R' U R D' R2 / R' D R2 U2 R' U2 R U R D' R2", "R' U' R2 U' R2 U2 R U' R U2 R' / U' R2 D R' U' R D' R2 U2 R U R'", "U R U2 R2 F' R U2 R U2 R' F / R U' R' U R L U' R' U R L' U R' / R U' R' U2 R U2 R' U2 R U R' U2 R U' R'", "U R U2 R' U2 R U2 R'", "U2 R U2 R' U R U2 R' L U' R U R' L'", "U' R U' R' U' R U R' U2 R U2 R' / U R U2 R' U R2 D R' U' R D' R2", "R U2 R' U2 R U' R' U R U' R' U' R U' R'", "U R' D R2 U2 R' U2 R U2 R D' R2 / U R U2 R' U2 R2 D R' U2 R D' R2 / U R U' R2 D' R U2 R' D R2 U2 R' / R U' R' U R U2 R' U' R U' R' U' R U R'", "U R U2 R' U2 R U' R' U R U2 R'", "U R U R' U2 R U' R' U2 R U R'", "U' R U' R' U R U' R' U2 R U R'", "R U R' U2 R U' R' U R U2 R' U R U' R'", "R U' R U R' U R U2 R2 / U' R U' R' U' L U' R U R' L' / R U2 R' U2 R U' R' U R U R'", "U R U R' L U' R U R' L' / U R U R' U' R U' R' U2 R U' R' U2 R U2 R'", "U2 R U2 R' U R U' R' U R U' R'", "U R U2 R' U R U' R'", "U' R U R' U R U2 R' U' R U R'", "R U' R' U R U' R' U R U R'", "R U2 R' U R2 U R' U R U2 R2 / R U2 R' U R U' R' U2 R U' R' U R U R'", "U2 R U2 R' U R U' R' U2 R U2 R'", "R' U' R2 U' R2 U2 R U2 R U' R'", "U2 R U R' U' R U2 R' U2 R U' R'" ],
    "11": [ "R U' R' U2 R U R'", "R U L' U2 L U' R' U L' U2 L / U2 R U R' U R2 D R' U' R D' R2 / U' L' U' L U' L' U2 L U R U2 R'", "R U' L U' R' U' L' U' L U' L'", "U2 R U R' L' U2 R U2 R' U2 L", "U' L' U' L U' L' U2 R L U' R'", "R U' L U' R' U L'", "U2 L U' R U R' L'", "R U' R' U2 R L' U R' U' L / R U' R' U2 R U2 R' U R U2 R'", "R' U2 R' U R2 U' R U2 R / U2 R U R' U2 R U' R' U R U2 R'", "U' L U' R U R' L' U R U' R'", "R U R' U' R U2 R U' L' U R2 U' L", "R U L' U2 L U' R' U2 L' U L", "U' L' U' L U' R L' U R' U2 L", "U2 L U' R U L' U2 R' U' R U' R'", "R2 U2 R U' R U R' U2 R2 / R U2 R' U2 R U2 R' U R U R'", "U' R U2 R' U R U2 R' U' R U R'", "R2 U' L' U R' U' L U' R' / U2 R U R' U2 R2 D R' U2 R D' R2 / U2 R U2 R2 D' R U2 R' D R2 U2 R'", "L U L' U L U2 R U' R' U L'", "U' L' U R U' L U' R' / R U2 R2 D' R U' R' D R", "U' R U R' U2 R U2 R' U R U' R'", "U2 R U R' U2 R U2 R'", "U R U R' F' R U R' U R U2 R' F", "R U R' U R U R' U' R U R'", "U2 R U R2 F' R U2 R U2 R' F / U R U' L U L' U2 R' U' L U2 L'", "U' R U R' U2 R U2 R' U2 R U2 R'", "U R U' R' U2 R U' R' U R U' R'", "R U R' U' R U2 R2 D' R U2 R' D R / U R U' R' U2 R U' R' L' U R U' R' L / R U' R' U2 R U R' U' R U2 R' U' R U' R'" ],
    "12": [ "R U2 R' U' R U2 R' U R U2 R'", "R L U2 R' U' R U R' U L' / U2 R2 D R' U R D' R2 U2 R U' R' / U R' U' R U' R' U2 R2 U R' U2 R U' R'/ R U R' U2 R U R' U2 R U R' U R U R' / R U' R' U R U R' U R U2 R' U R U2 R'", "U2 R L U2 L' U' L U' R' L' / U2 R U2 R U2 R' U' R U' R' U2 R' / R U' R' U R U' R' U2 R U R' U2 R U R' / R U R' U' R U' R' U2 R U R' U2 R U2 R'", "U' R U2 R' L' U R U' L U' R' / R U2 R' U' R U R' U' R U R' U R U2 R'", "U R2 D R' U2 R D' R2 U' R U2 R' / U R U' R' U R U' R' U' R U R' U2 R U' R'", "U' R U2 R' U' R U R' U R U' R'", "U R U L U2 L' U' L U' R' L' / U R U' R U2 R' U' R U' R' U2 R' / R U R' U' R U2 R' U2 R U2 R' U R U2 R'", "R U' R' L' U2 L U L' U R L U R' / R2 D R' U R D' R' U2 R' U' R U R' / R U2 R' U' R U2 R' U R U' R' U R U2 R'", "R U R' U' R U2 L U' R' U L' / U R U2 R' U' R U R' U2 R U' R'", "R U' R D R' U' R D' R2 U' R U R' / R U2 R' U' R U R' U2 R U2 R' U' R U' R'", "R U L' U R' U' R L U R' / U' R U' R' U2 R U2 R' U R U' R'", "R' U' R2 U' R U R' U' R U2 R / R U' R' U2 R2 D R' U R D' R' U R' / R U R' U' R U2 R' U2 R U' R' U' R U' R'", "U' R U R' U' L' U R2 U' L U R2 / R U' R2 U' R U' R U R' U' R' U2 R / U R U' R' U2 R U R' U' R U2 R' U' R U R' / U' R U2 R' U' R U R' U R U R' U' R U' R'", "U2 R2 D R' U R D' R2 U' R U2 R' / R U2 R' U2 R U2 R2 D' R U R' D R / U R U R' U' R U2 R' U' R U R' U2 R U' R'", "R U2 R' U' R U R'", "U' R' U2 R2 U R2 U R2 U R' / R U' R' U R U R' U R U' R' U' R U' R'", "U' R U2 R' U' R U R' U2 R U2 R' / U R2 D R' U2 R D' R2 U2 R U' R'", "R U R' U' R U2 R' U2 R U R'", "R U2 R' U R' D' r U2 r' D R / U R U2 R' U2 R U' R' U2 R U' R' U2 R U' R'", "U R' U' R U' R' U2 R2 U R' U' R U2 R' / R U' R' U2 R U' R' U R U R' U' R U2 R'", "R U2 R' U R L U' R' U L' / U2 R U R' U' R U R' U2 R U' R'", "U' R U2 R' U R U' R' U2 R U R'", "R U2 R' U' R U' R' U' R U' R'", "U' R U2 R' U' L U' R U R' L' / R U' R' U' R U R' U' R U R' U2 R U R'", "U' R U' R' U2 R U2 R' U2 R U2 R'", "R2 U2 R' U' R U' R2 U' R U R' / U R U2 R' U' R U R' U' R U2 R'", "U2 R U R' U' R U R' U' R U2 R'" ],
    "13": [ "L' D2 L U2 L' D2 L/U D' R' D R U' R' D' R D", "U' R U' R' U' R U2 R'", "U2 R' D' R2 U2 R' U' R U' R2 D R", "R U R' U' R U' R' U2 R U2 R' / D R' U2 R U' R' U' R", "U' R U' R' U L' U R U' R' L", "U L U' R U L' U' R'/U R U' F U R' U' R F' R'", "R U R' U' R U' R' U R U' R'", "R U' R2 U2 R U R' U R2 U R'", "R U2 R' U R2 U2 R' U' R U' R2", "R2 U R' U R2 U' R2 U R' U2 R2", "R' U R U' R U' R' U2 R U' R2' U' R", "U R' U2 R U R U' R2 U2 R2 U' R'", "R U2 R' U2 R' U' R U' R' U2 R2 U' R'", "U R2 U R' U R U2 R' U R'", "U2 R U' R' U2 R U2 R' U' R U2 R'", "U2 R U R2 U2 R2 U R2 U R / U' R U' R' U2 R U R' U' R U' R'", "R U' R U2 R' U' R U' R2 / R U2 R' U' R U' R' U R U2 R' U R U R'", "U' R U' R2 D' R U2 R' D R2 U' R' / U R U' R' U R U R' U2 R U R' U' R U2 R'", "U' R U' R' U2 R U' R'", "U' R U' R' U' R U' R' U R U2 R'", "U L U' R U R' L' U R U2 R'", "U' R U' R' U2 R2 D R' U' R D' R2", "U2 R U' R' U2 R U2 R' U2 R U' R'", "U R U R' U R U R' U' R U2 R'", "R U R' U' R U' R' L' U R U' R' L / R U' R' U R' U' R U' R' U2 R2 U' R'", "U' R U' R' U' R' U' R2 U' R2 U2 R", "U R U2 R' U' R U R' U R U R'" ],
    "14": [ "L D' L' U L D L'/U R' D' R U' R' D R", "U' L2 D' L' U2 L D L' U2 L' / U' R U R' U' R U' R' U' R U R'", "U R U L U' R' U L' / U R U2 R' U2 R U R' U R U' R'", "L2 D' L' U L D L' U' L' / U R U2 R' U2 R U R' U2 R U2 R'/R' D R' U R D' R' U' R2", "U' R U2 R' U R U R'", "U2 R2 U' L' U R2 U' L / U' R U2 R' U R U2 R' U R U2 R'", "D R' U R U R' U2 R D'", "D R' U R U2 R' U R D'", "R' U R U2 R2 U' R U2 R' U' R2", "U R U R' U2 R U R'", "R U' R' U2 R U' R U2 R2 U' R2 U' R2 / R U2 R' U' R U2 R' U' R U' R' U2 R U R'", "L U2 L' U' L2 D' L' U' L D L2 / U' R U' R' U' R2 U R' U R U2 R2", "U2 R U' R' U2 R U R' U R U R'", "D' L2 U' L U' L' U2 L U' L D / U2 R U' R' U R U' R' U' R U R'", "U' R U L' U R' U' R L U' R' / R U R' U R U R' U2 R U2 R' U2 R U' R'", "U2 R U2 R' U R U2 R' U2 R U R'", "U R U' R' U R U R' U' R U R'", "L2 D' L' U L D L2 U L U2 L' / U2 R U R' U R2 U2 R' U' R U' R' U R' / U R U R' U2 R U R' U' R U2 R' U' R U' R'", "U R' D' R U R' U' R U' R' U2 D R / L D' L' U L D L2 U' L U' L' U2 L", "U2 R U R2 U' R U' R' U2 R2 U2 R' / R U R' U' R U R' U2 R U R' U' R U2 R'", "U R U R' U2 R U2 R' U R U2 R'", "U R U' L' U2 L U' R' U2 L' U L / R U' R' U2 R U R' U2 R U' R' U R U' R'", "U' R U2 R' U' R L U' R' U L'", "L' U2 R U' R' L U L' U R L U' R' / U R U R' U2 R U R2 U2 R U R' U R / R U2 R' U' R U R' U2 R U' R' U R U' R'", "U' R U2 R' U R U' R' U' R U' R'", "U2 R U2 R' U R U2 L U' R' U L' / D' L' U' L U' L' U' L U L' U2 L D", "U' R U2 R2 U2 R U R' U R2 U' R' / R2 D R' U' R D' R' U' R' U' R U' R' / R U2 R' U' R U R' U2 R U' R' U2 R U2 R'" ],
    "15": [ "L' R U R' U' L R U2 R' U' R U R'", "R2 U2 R' U' R U' R' U2 R'", "R U2 R' U2 R U2 R' U' R U R'", "R U R' U' R U2 R' U' R U R'", "U2 R U' R' U' R U R' U' R U2 R'", "U' R2 U2 R' U' R U' R2 U' R U' R'", "R U' R' U2 R U' R' U2 R U' R' U2 R U' R'", "R U2 R' U2 R U R' U' R U2 R' U2 R U R'" ],
    "16": [ "U2 R U' R' U R U2 R' L' U R U' R' L", "R U2 R U R' U R U2 R2", "R U' R' U R U2 R' U2 R U2 R'", "R U' R' U R U2 R' U R U' R'", "R U2 R' U R U' R' U R U R'", "U' R U R' U R2 U R' U R U2 R2", "R U2 R' U2 R U' R' U R U2 R' U2 R U' R'", "R U' R' U2 R U2 R' U R U' R' U2 R U2 R'" ],
    "17": [ "U2 R2 U2' R2' U' R2 U' R2'", "U' R U R' U' L U' R U R' L'/U D' R' D F2 D' R D R' F2 R", "U2 R U' R' U L U' R U R' L'/U R' D' U' R U R' D R U' R' U R", "U2 R L U L U' R' U L' U' L' / U' R U2 R' U2 R U2 R' L' U R U' R' L / U' R U2 R' U2 R U R' L U' R U R' L'", "U2 R U' R' U R U R' U R U' R'", "U' R U R' U' R U R' U R U' R'", "U R U2 R' U' R U2 R' U' R U2 R'", "U2 R U' R' U' R U' R' U2 R U R'", "U R U R' U' R U2 R' U R U' R'", "U' R U R' L' U R U' L U' R'", "L' U2 R2 U2 R2 U' R2 U' R2 L", "R U R' U' R U R' U' R U R'", "R U' R2 U' R U' R' U2 R2 U R'", "U R U R' U' R U2 R' U2 R U2 R'", "U' R U R' U R U' R' U2 R U R'", "R U2 R' U' R U' R' U R U' R' U2 R U' R'", "U' R U2 R' U2 R U2 R' U R U' R'", "y L' U' L U L' U' L U L' U' L", "U2 F' R U R' U R U2 R' F", "U' R U R' U' R U R' U2 R U2 R'", "U R U' R' U R U' R' U R U R' U' R U' R'", "R U R' U2 R U2 R' U2 R U R'", "L' U' L U' L' U' R2 U' L U R2", "R U R' L U' R U R' U' R U R' L'", "R U' R' U2 R2 D R' U2 R D' R' U R'", "U R U2 R' U' R U2 R' U2 R U' R'", "U2 R U2 R' U2 R U' R' U R U' R'" ],
    "18": [ "R' D' R U R' D R2 U' R'", "U R U' R' U2 R L' U2 L U L' U R' L", "U' R U R' U R2 U2 R' U' R U' R2", "U' R' D' R U' R' D R U2 R U' R'", "R U' R' U2 R' U' R2 U' R2 U2 R", "R U' R' U' R U2 R' U' R U2 R'", "U2 R U' R' U2 R U2 R'", "R U' R' U' R U' R' U2 R U' R'", "U R U2 R U2 R' U' R U' R2", "U R U R' U' R U' R' U2 R U R'", "R U' R' U R U' R'", "U R U' R' U R U R' U' R U' R'", "R U R' U R U R' U2 R U2 R'", "R U' R' U' R U' R' U' R U2 R'", "R U2 R' U2 R U' R' U2 R U R'", "R U R' U2 R' U' R2 U' R2 U2 R2 U' R'", "R U2 R U2 R2 U' R2 U' R2", "R U' R' U L U' R U L' U' R'", "U' R U2 R' U' R U2 R' U2 R U2 R'", "U L R U' R' U R U' R' U L'", "U' R2 U R' U R U2 R2 U2 R U R'", "U' R U' R' U2 R U' R' U R U2 R'", "R U' R' L' U R U' R' L", "U' R2 U R' U R U L' U R2 U' L", "R U R' U2 L' U R U' L U' R'", "U R' U' R U' R' U2 R2 U' R' U2 R U2 R'", "R U R' U R U' R' U R2 U2 R' U' R U' R2" ],
    "19": [ "U' F' R U2 R' U2 R' F R2 U R' / R U R' U' R U R' U' R U R' U R U2 R'", "U' R U R2 D' R U' R' D R / F' R U2 R' U' R U R' U2 R' F R", "U R U2 R2 U' R U' R' U2 R2 U R'", "U L' U2 R U2 R' U2 R L U R'", "U R U' R' U2 R2 U2 R2 U' R2 U' R2 / U2 R U R' U2 R U R' U R U R'", "U2 R U2 R' U R U2 R' U R U R' / R2 D R' U R D' R2 U' R U R'", "U' R U2 R' U2 R U R'", "R U R' U' R U2 R' U R U2 R'", "U L' U2 R U2 R' U2 R U R' U' L", "U' R U2 L U' R' U L'", "L' R U R' U' R U R' U' L", "R U R' U R L U' R' U L'", "U' R U' L U' R' U L' U R U R' / R U' R U2 R' U' R U' R2 U' R U R'", "U2 R U' R2 U' R U' R' U2 R2 U2 R'", "U' R U2 R' U2 R L' U R' U' L", "U L' U R U L U L' U L U' R'", "U2 R U2 R2 D' R U2 R' D R", "U L U' R U R' U' R U R' L'", "R U R' U' R U R'", "R U R' U' R U' R' U' R U' R'", "U' R L' U2 L U' R' U2 L' U L / R U R' U' R U' R2 U' R2 U' R2 U2 R", "U' R U2 R' U2 R U' R' U' R U' R'", "R U R' U' R U R' U2 R U2 R' U' R U' R'", "R U2 R' U2 R U' R' U R U R' U' R U2 R'", "U2 R U2 R U' L' U R2 U' L / U R U2 R' U' R U' R' U' R U R' U' R U R'", "L' R U R' U' R L U R'", "R2 U2 R' U' R U' R' U R' U2 R U2 R' / U R U2 R' U2 R2 D R' U2 R D' R' U R' / R U' R' U' R U' R' U2 R U2 R' U2 R U2 R'" ],
    "20": [ "R' U' R' U' R' U R U R", "U R U' R' U R U L U' R' U L' / U2 R U' R2 D' R U2 R' D R2 U R'", "R U' R' U' R2 D R' U R D' R2 /R' F' R U R U' R' F / U' R U R' U' R U R' U' R U' R' U2 R U2 R'", "R2 D' R U' R' U' R U R' D R2 U R / U2 L' U2 R U L U' L' U' R' U2 L / R U' R' U R U2 R' U R U2 R' U R U' R'", "R U R' L' U R U' R' L U R U R'", "U' R U R' L U' R U L' U' R'", "U R U L U' R' U R L' U' R'", "U' R U R' U' R U' R U2 R2 U' R2 U' R2", "U' R U R' U' R U2 R' U' R U2 R' U' R U R'", "U F' U2 L' U L U L' U L F", "U' L U2 L' U2 R U L U' L' U' R'", "U F' R U R' U' R' F R", "R U R' L U' R U R' L' U R U2 R'", "U R2 U R2' U R U' R U' R2'", "R U2 R' U R U2 R' U2 R U' R'", "U R U' R2 U2 R2 U R2 U R", "U' R U' R' U2 R2 U' L' U R2 U' L", "U2 R U' R' U2 R U' R' U' R U R'", "U R' U' R2 U' R2 U2 R2 U R'", "U' R U R' U2 R U2 R' U' R U2 R'", "U2 R2 U R' U R' U' R2 U' R2", "R U2 R' U R U' R' U2 R U' R'", "R U2 R' U R U2 R' U' R U2 R'", "U R U R' U2 R U2 R' U2 R U' R'", "U R U R' U2 R U R' U' R U2 R'", "R U' R' U' R U' R' U R U R'", "R U' R' U' R U R' U R U R'" ]
};

var sv = {
	"3":["U2 R' D' r U2 r' D R / R U' R' U L' U2 R U' R' U2 L"],
	"2":["L' U2 L R U' R' U L' U L / R U R' U' R U R' U R U2 R'", "R U' R' F' R U2 R' U2 R' F R / R U' L' U2 L U2 R' U2 L' U2 L / R U' L' U' L U2 R' U2 L' U L", "U2 L R U' R' U L'", "R U R'", "R U' L' U2 L U L' U L R' / R U R' U R' U2 R U R' U R", "R U R D R' U R D' R' U' R' / R U' R2 D' R U' R' D R2 U' R' / R U' R' U' R2 D R' U' R D' R2"],
	"1":["U L' R U R' U R U' R' U2 L / R U2 R2 D' R U R' D R2 U2 R'", "R U' R D R' U2 R D' R2'", "R U2 R' U R U2 R'", "R U' R' U R' D' R U2 R' D R2 U' R'", "U2 R U' R2 D' R U' R' D R", "R U2 R' U R U' R' U R U' R' U R U2 R'/ R U' R' U' R U R' U' R U R' U' R U' R' / U' L' U R2 U' L U R' U R'", "R U' R' U' R U R' U' R U' R'", "R U' R2 U' R2 U' R2 U2 R", "L' U2 L U L' U L R U2 R'", "R U' R' U' R U' R'", "R U2 R' U' L' U R U' R' L", "R U2 R' U2 R' D' R U2 R' D R2 U' R' / R U' R' L' U R U' R' L U' R U' R'"],
	"0":["U2 L R U' R2 U L' U' R / U2 L R U' R' U2 L' U L U2 L' / U2 R U R' U2 R U R' U2 R U2 R'", "R U2 R' U R U' R' U R U2 R'", "R U R2 U2 R U R' U R", "R U2 R D R' U' R D' R2'", "R U' R' U' R U' R2 U' R U' R' U2 R", "R U R' U R' U' R U' R' U2 R", "U' R U R D R' U R D' R2'", "R U' R' U2 L' U R U' R' L"],
};

var c2 = {
	"3":["L' U2 R U' R' U2 L U R U R' / U' R U2 R D R' U2 R D' R' U' R'"], 
	"2":["U' R U R' U R U' R' U' R U' R'", "R' U' R U' R' U2 R2 U R' U R U' R'", "U R U2 R2 U' R U' R' U2 R2 U2 R' / U R' U2 R2 U R2 U R U2 R U' R'", "U2 R' U' R U' R U R2 U R / R U2 R' U2 R U' R' U' R U2 R'", "R L U L' U L U2 L' U' R' / U2 R2 D R' U' R D' R2 U' R U R' / R U2 R U R' U R U2 R' U R'", "U R U R2 D' R U2 R' D R"], 
	"1":["U R U' R' U R U2 R' U2 R U R'", "U' R U2 R' U' R2 U R' U R U2 R2 / U R U R' U R U2 R' U R U' R' U' R U' R'", "U R U R' U R U2 R' U R U R'", "R' D' R U R' D R2 U R'", "R U R2 U' R2 U' R2 U2 R2 U R'", "U2 R U2 R' U' R U2 R' U2 R U R'", "U' R U R' U R U R'", "U R U' R' U2 R U R' U' R U R'", "U' R U R' U R U2 R' U R U2 R'", "U2 R U' R' U' R U R'", "U' R U2 R D R' U R D' R2 / U' R U' R2 D' R U R' D R / L U' R' U L' U' R2 U' R'", "R U2 R' L U' R U L' U' R'"], 
	"0":["U' L' U2 L U L' U R L U' R'", "U R U R' U' R U R' U2 R U R'", "R U' R' U R U R' U' R U2 R'", "R2 D R' U R D' R' U R'", "R' U2 R U2 R U R' U' R' U R2 U' R' / R U R' U' R U2 R' U R U' R' U2 R U' R'", "U R U R U' L' U R2 U' L / U2 R' U' R U' R U R' U' R' U2 R", "U R' U2 R U R' U R U' R U2 R' / U' L' U2 L U L' U L U R U2 R'", "R U2 R' U2 R U' R' U2 R U' R'"],
};

var c3 = {
	"3":["U' L U' R U2 L' U2 R' U2 L U' L'"], 
	"2":["R' U2 R U' R U2 R' U2 R' U' R2 U' R'", "U2 R U2 R' U R U2 R' U R U' R'", "R U R' U2 R U' R' U R U R'U' R U R'", "R U' R' U R U2 R' U R U2 R'", "R' U' R' U' R U R U R2 U R'", "R U2 L' U R' U' L U R U2 R'/R2 D R' U R D' R2'", "R U R' U2 R U R' U2 R U R'"], 
	"1":["U2 R U R' U R U' R' U R U R'", "U R' U2 R2 U R U' R' U R2 U' R' U2 R", "R U2 R' U2 R U' R' U R U2 R' U2 R U R'", "U R U2 R' U2 R U R' U2 R U' R'", "R2 U' R' U2 R2 U R' U2 R2 U' R' U2 R", "U R U2 L U' R' U L' R U' R'", "R U' R2 U2 R U R' U R2 U' R'", "R U' R' U R U R'", "R2 U2 R2 U' R2 U' R2 U' R U R'", "R2 U' R' U2 R2 U R' U2 R U R", "U' R2 U R' U R U2 R2"], 
	"0":["U' R U R' U R U2 R' U R U' R'", "U' R U' R' U R2 U R' U R U2 R2", "R U' R' U R U' R' U' R U' R'", "U R U2 R' U2 R U R' U' R U2 R'", "R U2 L' U R' U' L R U' R'", "R U2 R' U' R U' R' U' R U R'", "R2 D R' U2 R D' R' U' R'", "U2 L U' R U R' L' U' R U R'"], 
};

var c4 = {
	"3":["R U' R' D R D R' U R D' R' D' / U R' U2 R U R' U R2 U2 R' U' R U2 R' / R U2 R' U2 R U2 R' U' R U' R' U R U2 R'"], 
	"2":["U' R U R' U R2 U2 R' U' R U' R' U' R' / U' R U' R' U' R' U' R U' R' U2 R2 U R' / R U R' U' R U' R' U R U R' U2 R U R'", "U R U' R' U2 R U2 L U' R' U L' / U R U2 R' U' R U R' U' R U R' U R U' R'", "R' D' R U2 R' D R2 U R' / U2 R U R' U' R U R' U' R U R' U R U' R'", "R' U2 R2 U R' U' R' U2 R", "U' R U2 R' U R' U2 R2 U R2 U R U' / R U R' U2 R U R' U2 R U R' U2 R U' R'", "D R2 U2 R' U R U R2 D' / U' R2 U R2 U R2 U2 R' U R' / R U' R' U2 R U R' U' R U' R' U2 R U2 R'"], 
	"1":["R D' R2 U2 R2 U' R2 U' R2 U' D R' / R' U2 R2 U R' L U2 R' U' R U2 L' / R U' R' U R U' R' U' R U' R' U R U2 R'", "R2 U2 R' U' R U' R2 U R U2 R'", "R' U2 R2 U R2 U R", "R2 D R' U2 R D' R' U R' / R U R' U2 R U R' U2 R U R' U' R U2 R'", "U R U' R' U2 R U2 R' U2 R U R'", "U R U' R' L U' R U R' U' R U R' L' / R U' R' U' R U2 R' U' R U R' U R U R'", "R2 U2 R U' R' U R' U2 R' U' R' / R U' R' U2 R U R' U' R U' R' U R U' R'", "R U' R' U R U' R' U2 R U' R'", "R' U2 R2 U R D' R U R' D R2 / U2 R' U2 R U R' U R U' R U R' U2 R U' R' / U2 R U2 R' U R U' R U R' U R U2 R' U' R'", "R2 U2 R' U' R U' R' U' R' / R U' R' U R U' R' U' R U2 R'", "R' U2 R2 U R2 U R2 U2 R' U' R U' R' / U R U R' U2 R U2 R' U2 R U2 R' U' R U2 R'", "U R U R' U2 R2 D R' U2 R D' R' U R' / U' R U R' U R U2 R' U2 R U2 R' U2 R U' R'"], 
	"0":["R' D' R U2 R' D R2 U2 R' U R U2 R' / R U R' U2 R U2 R' U R U2 R' U' R U2 R'", "R' U2 R2 U R2 U' R U R' U R / R U R' U R U' R' U' R U R' U R U R'", "U R U' R' U' R U R' U' R U R'", "U2 R U2 R' U' R U R' U' R U R'", "R U2 R' U2 R U2 R' U2 R U' R'", "U2 R' U' R U' R' U2 R2 U R'", "U R U' R' U' R L' U R' U' R L U R' / U' R' U' R U' R' U2 R U' R U2 R' U' R U R'", "R U2 R' U2 R U2 R' U' R U2 R'"], 
};

var wv = {
	"3":["U L' U2 R U R' U2 L / U' L' U2 R U' R' U2 L / y' U r D r' U' r D' r' / y2 L F L' U' L U L F' L2 "], 
	"2":["U R U' R' ","R' F R U R U' R' F' / U' L U' R U L' U R' ","U R2 D R' U' R D' R2 ","U R U' R' U R' U' R U' R' U2 R / U R U' R' U2 R U2 R' U' R U' R' ","R U' R' U2 R U' R' U2 R U R' ","U R U R' U' R U' R' / R' U' R U R U' R' U' R' U R"], 
	"1":["U2 R U' R' U R U2 R'","U2 F' R U2 R' U2 R' F R / U L' U2 R U L U' L' U R' U2 L ","R' F R2 U R' U' R U R' U' F' / U R U R2 U' R2 U' R2 U2 R / U2 F2 L' U L U L' U' L F2 ","U2 R' U' R2 U' R2 U2 R ","U R U2 L U L' R' U2 L U L' / R' F2 R F2 U L' U L ","U2 R U2 R2 U' R U' R' U2 R / U' F2 L' U L U' L' U' L F2 ","U2 R2 D R' U2 R D' R2 / U2 L' U R U' L U2 R' ","L' U R U' R' L / r' F R F' M' / L' U R U' M' x' ","U2 L' R U R' U' L R U2 R' / U2 M x U R' U' L R U2 R' / U2 R U' R' U' R' F R U R U' R' F' / U R' D' R U R' D R2 U2' R' ","U2 R U2 R' ","R' F' R U2 R U2 R' F / U L' U2 R U' R' U2 L U R U' R' ","R' F2 R2 U' R' U' R U R' F2 / U2 L' U R U' R' L U' R U' R' ","U R U' R' U' R U R' U R U2 R' / U L' U2 L R U R' U L' U L "], 
	"0":["U2 R U' R D R' U' R D' R2 / U R U' R2 U2 R U R' U R / U2 R2 D R' U' R D' R' U' R' ","U R U R D R' U2 R D' R2 / U R2 D R' U R D' R' U2 R' ","R2 U R' U R' U' R U R U2 R2 / U2 R' U L U' R2 U L' U R' / U2 R U' R' U L' U R U' R' L U' R U' R' / U2 R U R' U' R U R D R' U R D' R2' ","U2 R U' R' U R U' R' U R U2 R' ","U2 R U2 R2 U2 R U R' U R / U2 R U' R' U R U' R D R' U' R D' R2 ","U R U' R2 U' R U' R' U2 R / U R U R' U F2 L' U L U' L' U' L F2 ","U R U R' U' R U R' U' R U' R'"],
};

var wvSonc = {
	"3":["R U' R D R' U R D' R' U' R'"], 
	"2":["R U' R'", "U' R' F R U R U' R' F'", "R2 D R' U' R D' R2", "R U' R' U R' U' R U' R' U2 R", "U' R U' R' U2 R U' R' U2 R U R'", "R U R' U' R U' R'"], 
	"1":["U R U' R' U R U2 R'", "U F' R U2 R' U2 R' F R", "R U R2 U' R2 U' R2 U2 R", "U R' U' R2 U' R2 U2 R", "R U' x' U R' D R U' R' D' x", "U R U2 R2 U' R U' R' U2 R", "U R2 D R' U2 R D' R2", "U' L' U R U' R' L", "U R U' R' U' R' F R U R U' R' F'", "U R U2 R'", "R U' R' U2 R2 D R' U2 R D' R' U2 R' / U' R' F2 R2 U' R' U' R U R' F2'"], 
	"0":["R U' R' U' R U R' U R U2 R'", "R U' R2 U2 R U R' U R", "R2 D R' U R D' R' U2 R'", "R U' R' U2 R U2 R2 U' R2 U' R2 U2 R", "U R U' R' U R U' R' U R U2 R'", "U R U2 R2 U2 R U R' U R", "R U' (R2 U' R U' R' U2 R", "R U R' U' R U R' U' R U' R'"], 
};

var c6 = {
	"3":["R L U2 L' U2 R' U2 L U2 L'"], 
	"2":["U' R2 U2 R2 U' R2 U' R' U' R' / R D L U2 L' U L U L' D' R'", "R U' R' U' R U2 R' L' U R U' R' L", "D R2 U' R' U' R U2 R2 D'", "U L U' R U' L' U' L U' L' U R'", "R' D' R U2 R' D R U R U' R'", "L U' R U L' U R' U' R U2 R' / U R U R' U R U' R' U' R U2 R'"], 
	"1":["R U R' L' U R U' R' U R U' R' L", "R U R' U R' D' R U R' D R2 U' R'", "U R U2 R2 D' R U2 R' D R2 U R'", "U' R U2 R' U' R U' R' U R U2 R'", "R U' R' U' R U2 R' U R U' R'", "L' U L U' R L' U' R' L U2 L' U2 L", "U' R U2 R2 D' R U2 R' D R2 U' R'", "U' R U2 R2 D' R U' R' D R2 U2 R'", "R U' R' U' R U2 R' U2 R U2 R'", "U2 R L U2 R' U2 R U2 R' L' / R' D' R U2 R' D R U2 R U2 R'", "U' R U2 R' L' U2 R U' R' U2 L / U R U R' U R U' R' U2 R U' R'", "U' R U2 R' U' R U2 R'"], 
	"0":["R U R' U R U' R' U R U' R'", "R U R' U R U' R' L' U R U' R' L", "U' R U2 R' L U' R U L' U R'", "U2 R U' R' U2 R U R' U' R U2 R'", "U' R U2 R' U L' U R U' R' L", "U2 R2 U' L' U R' U' R' U R U' R' L / R U' R' U2 R U' R' U R U' R' U R U R'", "U' R U2 R' U2 R U' R'", "R U R' U R U' R' U2 R U2 R'"],
};

var c7 = {
	"3":["U' R U R2 D' R U2 R' D R2 U' R'"],
	"2":["U R2 U R U R' U' R' U' R2/ U2 R U R' U2 R U' R' U' R U R'", "L U' R U R' U' R U L' U R' / U' R U R' U2 R2 D R' U' R D' R2", "R' D' R U R' D R U R U' R'", "U' R U R2 D' R U' R' D R2 U2 R' / U2 R U' R U R' U R U2 R' U R'", "R U2 R' U' R U2 R' U' R U R'", "U' R U R' U' R U' R' U R U2 R'"], 
	"1":["U L R U' R' U L' R U' R' / U2 F R U R' U' R' F' R2 U' R'", "U' R U R' U L' U R U' R' L / U R U R2 F2 R U2 R U2 R' F2 / U R U' R2 F' R U R U' R' F", "U' R U R' U' F' R U2 R' U2 R' F R / R U' R' U2 R U R' U' R U2 R' U2 R U R'", "U' R U R' U2 R U R' U' R U' R'", "U' R U R' U2 R U' R'", "R U' R' U2 R U2 R' U' R U R'", "L' U' L U R U2 L' U2 R' L / U' R U R' L' U2 R U' R' U2 L", "U2 R U' R' U2 R U' R' U2 R U' R'", "U2 R2 U R2 U R2 U2 R' U' R' / U R2 U2 R2 U' R2 U' R2 U' R U' R' / R U' R' U' R U2 R' U' R U R' U2 R U' R'", "U' R' U' R U' R' U2 R U' R U R'", "U R U R' U R U2 R' U' R U2 R'", "U R2 U2 R2 U' R2 U' R' U2 R' / R U' L U2 L' U' L U' R' L' / R U R U2 R' U' R U' R' U2 R'"], 
	"0":["U' R2 U2 R' U' R U' R2 U2 R U' R' / R' U' R U' R' U R U' R' U2 R2 U R' / R U R' U' R U' R' U' R U R' U' R U2 R'", "U' R U R' U2 R U' R2 U' R U' R' U2 R / R U2 R D R' U2 R D' R2 U2 R U' R'", "R' D' R U R' D R U2 R U2 R' / U R U2 R' U2 R2 U R' U R U2 R2 / R U2 R' U2 R U' R' U2 R U2 R' U2 R U2 R'", "U D R2 U R2 U2 R U2 R U' R2 D' / U2 R2 U R2 U R2 U2 R2 U R U2 R' / R U R' U' R U R' U' R U2 R' U' R U R'", "U' L U L' U L U2 R L' U' R' / U R U R' U R U2 R' U2 R U' R'", "U' R2 U2 R' U' R U' R2 U' R U2 R' / R U' R' U2 R U2 R' U' R U' R' U' R U' R'", "U' R U R' U' R U2 R'", "U R U2 R' U' R U' R' U R U R'"], 
};

var c8 = {
	"3":["R' D' R U' R' D R U R U' R'"], 
	"2":["R U2 R' U R U R' U2 R U2 R'", "U' R2 U R' U R2 U' R' U R' U2 R2", "L U L' U L U R U R' L'", "U2 R U R2 D R' U2 R D' R' U2 R2", "R U' R U2 R2 U' R2 U' R2", "R U2 R' U R U R' U R U' R'"], 
	"1":["U R U2 R' D R' U R U2 R' U R D'", "U2 R U R2 D R' U R D' R' U' R2", "U R U2 R2 D R' U R D' R' U' R2", "U R U2 R D R' U' R D' R' U R'", "U2 R U R' U' R U2 R' U R U R'", "R U' R' U R' U' R2 U' R2 U2 R2 U' R'", "U R U2 R2 D R' U2 R D' R' U2 R2", "R U2 R' U2 L' U R U' L U' R'", "U' R2 U2 R U' R' U R' U2 R2", "R L' U' L U' L' U2 L U' R'", "U R' U2 R' U R U' R U2 R2 U' R'", "R U R' U2 R U' R' U2 R U2 R'"], 
	"0":["U' R U' R U2 R U' R' U R' U2 R2", "R U R U R' U R U L' U R2 U' L / U2 R U R' U' R U2 R' U R U' R' U' R U' R'", "R U R U' L' U R2 U' L U2 R U R'", "U R U' R' U R2 U R' U R' U' R2 U' R2", "R U R' U2 R U' R' L' U R U' R' L", "R U2 R' U' L U L' U L U2 R U' R' U L'", "R U R' U2 R U' R' U R U' R'", "R U R' U L' U R U' R' L U R U' R'"], 
};

var c9 = {
	"4":["R2 U R' U R U2 R' U' R' / R U' R' U R U2 R' U R U R'"], 
	"3":["R U R' U R U2 R' U2 R U R'", "U2 R U R' U' R U' R' U2 R U' R'", "L U' R' U L' U' R U' R U R'", "U2 R U2 R' U' R U' R' U R U' R'", "U R U' R' U' R U' R' U R U' R'", "R' U' R U' R' U2 R U' R U' R'"], 
	"2":["U2 R2 U2 R' U' R U' R2 / R U' R' U' R U R' U2 R U R'", "R U R' U R U2 L U' R' U L'", "R U' R U' L' U R2 U' L", "U R2 U2 R' U' R U' R' U R'", "U' R U R' U' R2 U2 R' U' R U' R2", "R U' R' U R U2 R' U R U' R' U' R U' R' / U2 R2 U2 R' U2 L' U R U' L R2 /R' U2 R U R' U R2 U R' U2 R U2 R'", "R' U' R U' R' U2 R U' R U R' U' R U' R'", "U' R' U' R U' R' U2 R U R U2 R'", "R U R' U2 R U R' U' R U R'", "U' R U' R' U2 R2 U2 R' U' R U' R' U R'", "R U2 R' U2 R U R' U R U R'", "U L' U' L U' L' R U' R' U2 L"], 
	"1":["R2 U R' U R U2 R2 U R U2 R'", "R' U' R U' R' U2 R2 U2 R'", "U2 R' U2 R U R' U R2 U R'", "U' R' U' R U' R' U2 R2 U' R'", "U2 R U' R' U R2 U2 R' U' R U' R2", "U R' U2 R U R' U R2 U R' U R U R'", "R' U' R U' R' U R2 U' R2 U2 R", "U' R U2 R' U' R2 U2 R' U' R U' R2"], 
};

var c10 = {
	"4":["R U R' U R U2 R U R' U R U2 R2 / R U R' U R U R' U2 R U' R' U R U R'"], 
	"3":["U R U' R2 D' R U R' D R2 U' R' / R U R' U2 R U2 R U R' U R U2 R2 / R U' R' U R U R' U2 R U R' U2 R U R'", "U2 R U R' U' R U2 R' U' R U2 R'", "U R U2 R' U2 R U2 R2 U' R U' R' U2 R", "R U' R' U R2 D R' U R D' R2", "R U2 R' U2 R2 D R' U R D' R2 / R' D R2 U2 R' U2 R U R D' R2", "R' U' R2 U' R2 U2 R U' R U2 R' / U' R2 D R' U' R D' R2 U2 R U R'"], 
	"2":["U R U2 R2 F' R U2 R U2 R' F / R U' R' U R L U' R' U R L' U R' / R U' R' U2 R U2 R' U2 R U R' U2 R U' R'", "U R U2 R' U2 R U2 R'", "U2 R U2 R' U R U2 R' L U' R U R' L'", "U' R U' R' U' R U R' U2 R U2 R' / U R U2 R' U R2 D R' U' R D' R2", "R U2 R' U2 R U' R' U R U' R' U' R U' R'", "U R' D R2 U2 R' U2 R U2 R D' R2 / U R U2 R' U2 R2 D R' U2 R D' R2 / U R U' R2 D' R U2 R' D R2 U2 R' / R U' R' U R U2 R' U' R U' R' U' R U R'", "U R U2 R' U2 R U' R' U R U2 R'", "U R U R' U2 R U' R' U2 R U R'", "U' R U' R' U R U' R' U2 R U R'", "R U R' U2 R U' R' U R U2 R' U R U' R'", "R U' R U R' U R U2 R2 / U' R U' R' U' L U' R U R' L' / R U2 R' U2 R U' R' U R U R'", "U R U R' L U' R U R' L' / U R U R' U' R U' R' U2 R U' R' U2 R U2 R'"], 
	"1":["U2 R U2 R' U R U' R' U R U' R'", "U R U2 R' U R U' R'", "U' R U R' U R U2 R' U' R U R'", "R U' R' U R U' R' U R U R'", "R U2 R' U R2 U R' U R U2 R2 / R U2 R' U R U' R' U2 R U' R' U R U R'", "U2 R U2 R' U R U' R' U2 R U2 R'", "R' U' R2 U' R2 U2 R U2 R U' R'", "U2 R U R' U' R U2 R' U2 R U' R'"], 
};

var c11 = {
	"4":["R U' R' U2 R U R'"], 
	"3":["R U L' U2 L U' R' U L' U2 L / U2 R U R' U R2 D R' U' R D' R2 / U' L' U' L U' L' U2 L U R U2 R'", "R U' L U' R' U' L' U' L U' L'", "U2 R U R' L' U2 R U2 R' U2 L", "U' L' U' L U' L' U2 R L U' R'", "R U' L U' R' U L'", "U2 L U' R U R' L'"], 
	"2":["R U' R' U2 R L' U R' U' L / R U' R' U2 R U2 R' U R U2 R'", "R' U2 R' U R2 U' R U2 R / U2 R U R' U2 R U' R' U R U2 R'", "U' L U' R U R' L' U R U' R'", "R U R' U' R U2 R U' L' U R2 U' L", "R U L' U2 L U' R' U2 L' U L", "U' L' U' L U' R L' U R' U2 L", "U2 L U' R U L' U2 R' U' R U' R'", "R2 U2 R U' R U R' U2 R2 / R U2 R' U2 R U2 R' U R U R'", "U' R U2 R' U R U2 R' U' R U R'", "R2 U' L' U R' U' L U' R' / U2 R U R' U2 R2 D R' U2 R D' R2 / U2 R U2 R2 D' R U2 R' D R2 U2 R'", "L U L' U L U2 R U' R' U L'", "U' L' U R U' L U' R' / R U2 R2 D' R U' R' D R"], 
	"1":["U' R U R' U2 R U2 R' U R U' R'", "U2 R U R' U2 R U2 R'", "U R U R' F' R U R' U R U2 R' F", "R U R' U R U R' U' R U R'", "U2 R U R2 F' R U2 R U2 R' F / U R U' L U L' U2 R' U' L U2 L'", "U' R U R' U2 R U2 R' U2 R U2 R'", "U R U' R' U2 R U' R' U R U' R'", "R U R' U' R U2 R2 D' R U2 R' D R / U R U' R' U2 R U' R' L' U R U' R' L / R U' R' U2 R U R' U' R U2 R' U' R U' R'"], 
};

var c12 = {
	"4":["R U2 R' U' R U2 R' U R U2 R'"], 
	"3":["R L U2 R' U' R U R' U L' / U2 R2 D R' U R D' R2 U2 R U' R' / U R' U' R U' R' U2 R2 U R' U2 R U' R'/ R U R' U2 R U R' U2 R U R' U R U R' / R U' R' U R U R' U R U2 R' U R U2 R'", "U2 R L U2 L' U' L U' R' L' / U2 R U2 R U2 R' U' R U' R' U2 R' / R U' R' U R U' R' U2 R U R' U2 R U R' / R U R' U' R U' R' U2 R U R' U2 R U2 R'", "U' R U2 R' L' U R U' L U' R' / R U2 R' U' R U R' U' R U R' U R U2 R'", "U R2 D R' U2 R D' R2 U' R U2 R' / U R U' R' U R U' R' U' R U R' U2 R U' R'", "U' R U2 R' U' R U R' U R U' R'", "U R U L U2 L' U' L U' R' L' / U R U' R U2 R' U' R U' R' U2 R' / R U R' U' R U2 R' U2 R U2 R' U R U2 R'"], 
	"2":["R U' R' L' U2 L U L' U R L U R' / R2 D R' U R D' R' U2 R' U' R U R' / R U2 R' U' R U2 R' U R U' R' U R U2 R'", "R U R' U' R U2 L U' R' U L' / U R U2 R' U' R U R' U2 R U' R'", "R U' R D R' U' R D' R2 U' R U R' / R U2 R' U' R U R' U2 R U2 R' U' R U' R'", "R U L' U R' U' R L U R' / U' R U' R' U2 R U2 R' U R U' R'", "R' U' R2 U' R U R' U' R U2 R / R U' R' U2 R2 D R' U R D' R' U R' / R U R' U' R U2 R' U2 R U' R' U' R U' R'", "U' R U R' U' L' U R2 U' L U R2 / R U' R2 U' R U' R U R' U' R' U2 R / U R U' R' U2 R U R' U' R U2 R' U' R U R' / U' R U2 R' U' R U R' U R U R' U' R U' R'", "U2 R2 D R' U R D' R2 U' R U2 R' / R U2 R' U2 R U2 R2 D' R U R' D R / U R U R' U' R U2 R' U' R U R' U2 R U' R'", "R U2 R' U' R U R'", "U' R' U2 R2 U R2 U R2 U R' / R U' R' U R U R' U R U' R' U' R U' R'", "U' R U2 R' U' R U R' U2 R U2 R' / U R2 D R' U2 R D' R2 U2 R U' R'", "R U R' U' R U2 R' U2 R U R'", "R U2 R' U R' D' r U2 r' D R / U R U2 R' U2 R U' R' U2 R U' R' U2 R U' R'"], 
	"1":["U R' U' R U' R' U2 R2 U R' U' R U2 R' / R U' R' U2 R U' R' U R U R' U' R U2 R'", "R U2 R' U R L U' R' U L' / U2 R U R' U' R U R' U2 R U' R'", "U' R U2 R' U R U' R' U2 R U R'", "R U2 R' U' R U' R' U' R U' R'", "U' R U2 R' U' L U' R U R' L' / R U' R' U' R U R' U' R U R' U2 R U R'", "U' R U' R' U2 R U2 R' U2 R U2 R'", "R2 U2 R' U' R U' R2 U' R U R' / U R U2 R' U' R U R' U' R U2 R'", "U2 R U R' U' R U R' U' R U2 R'"], 
};

var c13 = {
	"3":["L' D2 L U2 L' D2 L / U D' R' D R U' R' D' R D"], 
	"2":["U' R U' R' U' R U2 R'", "U2 R' D' R2 U2 R' U' R U' R2 D R", "R U R' U' R U' R' U2 R U2 R' / D R' U2 R U' R' U' R", "U' R U' R' U L' U R U' R' L", "U L U' R U L' U' R'/U R U' F U R' U' R F' R'", "R U R' U' R U' R' U R U' R'", "R U' R2 U2 R U R' U R2 U R'"], 
	"1":["R U2 R' U R2 U2 R' U' R U' R2", "R2 U R' U R2 U' R2 U R' U2 R2", "R' U R U' R U' R' U2 R U' R2' U' R", "U R' U2 R U R U' R2 U2 R2 U' R'", "R U2 R' U2 R' U' R U' R' U2 R2 U' R'", "U R2 U R' U R U2 R' U R'", "U2 R U' R' U2 R U2 R' U' R U2 R'", "U2 R U R2 U2 R2 U R2 U R / U' R U' R' U2 R U R' U' R U' R'", "R U' R U2 R' U' R U' R2 / R U2 R' U' R U' R' U R U2 R' U R U R'", "U' R U' R2 D' R U2 R' D R2 U' R' / U R U' R' U R U R' U2 R U R' U' R U2 R'", "U' R U' R' U2 R U' R'", "U' R U' R' U' R U' R' U R U2 R'"], 
	"0":["U L U' R U R' L' U R U2 R'", "U' R U' R' U2 R2 D R' U' R D' R2", "U2 R U' R' U2 R U2 R' U2 R U' R'", "U R U R' U R U R' U' R U2 R'", "R U R' U' R U' R' L' U R U' R' L / R U' R' U R' U' R U' R' U2 R2 U' R'", "U' R U' R' U' R' U' R2 U' R2 U2 R", "U R U2 R' U' R U R' U R U R'"], 
};

var c14 = {
	"3":["L D' L' U L D L' / U R' D' R U' R' D R"], 
	"2":["U' L2 D' L' U2 L D L' U2 L' / U' R U R' U' R U' R' U' R U R'", "U R U L U' R' U L' / U R U2 R' U2 R U R' U R U' R'", "L2 D' L' U L D L' U' L' / U R U2 R' U2 R U R' U2 R U2 R'/R' D R' U R D' R' U' R2", "U' R U2 R' U R U R'", "U2 R2 U' L' U R2 U' L / U' R U2 R' U R U2 R' U R U2 R'", "D R' U R U R' U2 R D'"], 
	"1":["D R' U R U2 R' U R D'", "R' U R U2 R2 U' R U2 R' U' R2", "U R U R' U2 R U R'", "R U' R' U2 R U' R U2 R2 U' R2 U' R2 / R U2 R' U' R U2 R' U' R U' R' U2 R U R'", "L U2 L' U' L2 D' L' U' L D L2 / U' R U' R' U' R2 U R' U R U2 R2", "U2 R U' R' U2 R U R' U R U R'", "D' L2 U' L U' L' U2 L U' L D / U2 R U' R' U R U' R' U' R U R'", "U' R U L' U R' U' R L U' R' / R U R' U R U R' U2 R U2 R' U2 R U' R'", "U2 R U2 R' U R U2 R' U2 R U R'", "U R U' R' U R U R' U' R U R'", "L2 D' L' U L D L2 U L U2 L' / U2 R U R' U R2 U2 R' U' R U' R' U R' / U R U R' U2 R U R' U' R U2 R' U' R U' R'", "U R' D' R U R' U' R U' R' U2 D R / L D' L' U L D L2 U' L U' L' U2 L"], 
	"0":["U2 R U R2 U' R U' R' U2 R2 U2 R' / R U R' U' R U R' U2 R U R' U' R U2 R'", "U R U R' U2 R U2 R' U R U2 R'", "U R U' L' U2 L U' R' U2 L' U L / R U' R' U2 R U R' U2 R U' R' U R U' R'", "U' R U2 R' U' R L U' R' U L'", "L' U2 R U' R' L U L' U R L U' R' / U R U R' U2 R U R2 U2 R U R' U R / R U2 R' U' R U R' U2 R U' R' U R U' R'", "U' R U2 R' U R U' R' U' R U' R'", "U2 R U2 R' U R U2 L U' R' U L' / D' L' U' L U' L' U' L U L' U2 L D", "U' R U2 R2 U2 R U R' U R2 U' R' / R2 D R' U' R D' R' U' R' U' R U' R' / R U2 R' U' R U R' U2 R U' R' U2 R U2 R'"], 
};

var c15 = {
	"Cw":[ "L' R U R' U' L R U2 R' U' R U R'", "R2 U2 R' U' R U' R' U2 R'", "R U2 R' U2 R U2 R' U' R U R'", "R U R' U' R U2 R' U' R U R'", "U2 R U' R' U' R U R' U' R U2 R'", "U' R2 U2 R' U' R U' R2 U' R U' R'", "R U' R' U2 R U' R' U2 R U' R' U2 R U' R'", "R U2 R' U2 R U R' U' R U2 R' U2 R U R'" ],
};

var c16 = {
	"Ccw":[ "U2 R U' R' U R U2 R' L' U R U' R' L", "R U2 R U R' U R U2 R2", "R U' R' U R U2 R' U2 R U2 R'", "R U' R' U R U2 R' U R U' R'", "R U2 R' U R U' R' U R U R'", "U' R U R' U R2 U R' U R U2 R2", "R U2 R' U2 R U' R' U R U2 R' U2 R U' R'", "R U' R' U2 R U2 R' U R U' R' U2 R U2 R'" ],
};

var c17 = {
	"4":["U2 R2 U2' R2' U' R2 U' R2'"], 
	"3":["U' R U R' U' L U' R U R' L'/U D' R' D F2 D' R D R' F2 R", "U2 R U' R' U L U' R U R' L'/U R' D' U' R U R' D R U' R' U R", "U2 R L U L U' R' U L' U' L' / U' R U2 R' U2 R U2 R' L' U R U' R' L / U' R U2 R' U2 R U R' L U' R U R' L'", "U2 R U' R' U R U R' U R U' R'", "U' R U R' U' R U R' U R U' R'", "U R U2 R' U' R U2 R' U' R U2 R'"], 
	"2":["U2 R U' R' U' R U' R' U2 R U R'", "U R U R' U' R U2 R' U R U' R'", "U' R U R' L' U R U' L U' R'", "L' U2 R2 U2 R2 U' R2 U' R2 L", "R U R' U' R U R' U' R U R'", "R U' R2 U' R U' R' U2 R2 U R'", "U R U R' U' R U2 R' U2 R U2 R'", "U' R U R' U R U' R' U2 R U R'", "R U2 R' U' R U' R' U R U' R' U2 R U' R'", "U' R U2 R' U2 R U2 R' U R U' R'", "y L' U' L U L' U' L U L' U' L", "U2 F' R U R' U R U2 R' F"], 
	"1":["U' R U R' U' R U R' U2 R U2 R'", "U R U' R' U R U' R' U R U R' U' R U' R'", "R U R' U2 R U2 R' U2 R U R'", "L' U' L U' L' U' R2 U' L U R2", "R U R' L U' R U R' U' R U R' L'", "R U' R' U2 R2 D R' U2 R D' R' U R'", "U R U2 R' U' R U2 R' U2 R U' R'", "U2 R U2 R' U2 R U' R' U R U' R'"], 
};

var c18 = {
	"3":["R' D' R U R' D R2 U' R'", "U R U' R' U2 R L' U2 L U L' U R' L", "U' R U R' U R2 U2 R' U' R U' R2", "U' R' D' R U' R' D R U2 R U' R'"], 
	"2":["R U' R' U2 R' U' R2 U' R2 U2 R", "R U' R' U' R U2 R' U' R U2 R'", "U2 R U' R' U2 R U2 R'", "R U' R' U' R U' R' U2 R U' R'", "U R U2 R U2 R' U' R U' R2", "U R U R' U' R U' R' U2 R U R'"], 
	"1":["R U' R' U R U' R'", "U R U' R' U R U R' U' R U' R'", "R U R' U R U R' U2 R U2 R'", "R U' R' U' R U' R' U' R U2 R'", "R U2 R' U2 R U' R' U2 R U R'", "R U R' U2 R' U' R2 U' R2 U2 R2 U' R'", "R U2 R U2 R2 U' R2 U' R2", "R U' R' U L U' R U L' U' R'", "U' R U2 R' U' R U2 R' U2 R U2 R'", "U L R U' R' U R U' R' U L'", "U' R2 U R' U R U2 R2 U2 R U R'", "U' R U' R' U2 R U' R' U R U2 R'"], 
	"0":["R U' R' L' U R U' R' L", "U' R2 U R' U R U L' U R2 U' L", "R U R' U2 L' U R U' L U' R'", "U R' U' R U' R' U2 R2 U' R' U2 R U2 R'", "R U R' U R U' R' U R2 U2 R' U' R U' R2"], 
};

var c19 = {
	"3":["U' F' R U2 R' U2 R' F R2 U R' / R U R' U' R U R' U' R U R' U R U2 R'", "U' R U R2 D' R U' R' D R / F' R U2 R' U' R U R' U2 R' F R", "U R U2 R2 U' R U' R' U2 R2 U R'", "U L' U2 R U2 R' U2 R L U R'"], 
	"2":["U R U' R' U2 R2 U2 R2 U' R2 U' R2 / U2 R U R' U2 R U R' U R U R'", "U2 R U2 R' U R U2 R' U R U R' / R2 D R' U R D' R2 U' R U R'", "U' R U2 R' U2 R U R'", "R U R' U' R U2 R' U R U2 R'", "U L' U2 R U2 R' U2 R U R' U' L", "U' R U2 L U' R' U L'"], 
	"1":["L' R U R' U' R U R' U' L", "R U R' U R L U' R' U L'", "U' R U' L U' R' U L' U R U R' / R U' R U2 R' U' R U' R2 U' R U R'", "U2 R U' R2 U' R U' R' U2 R2 U2 R'", "U' R U2 R' U2 R L' U R' U' L", "U L' U R U L U L' U L U' R'", "U2 R U2 R2 D' R U2 R' D R", "U L U' R U R' U' R U R' L'", "R U R' U' R U R'", "R U R' U' R U' R' U' R U' R'", "U' R L' U2 L U' R' U2 L' U L / R U R' U' R U' R2 U' R2 U' R2 U2 R", "U' R U2 R' U2 R U' R' U' R U' R'"], 
	"0":["R U R' U' R U R' U2 R U2 R' U' R U' R'", "R U2 R' U2 R U' R' U R U R' U' R U2 R'", "U2 R U2 R U' L' U R2 U' L / U R U2 R' U' R U' R' U' R U R' U' R U R'", "L' R U R' U' R L U R'", "R2 U2 R' U' R U' R' U R' U2 R U2 R' / U R U2 R' U2 R2 D R' U2 R D' R' U R' / R U' R' U' R U' R' U2 R U2 R' U2 R U2 R'"], 
};

var c20 = {
	"4":["R' U' R' U' R' U R U R"], 
	"2":["U R U' R' U R U L U' R' U L' / U2 R U' R2 D' R U2 R' D R2 U R'", "R U' R' U' R2 D R' U R D' R2 /R' F' R U R U' R' F / U' R U R' U' R U R' U' R U' R' U2 R U2 R'", "R2 D' R U' R' U' R U R' D R2 U R / U2 L' U2 R U L U' L' U' R' U2 L / R U' R' U R U2 R' U R U2 R' U R U' R'", "R U R' L' U R U' R' L U R U R'", "U' R U R' L U' R U L' U' R'", "U R U L U' R' U R L' U' R'", "U' R U R' U' R U' R U2 R2 U' R2 U' R2", "U' R U R' U' R U2 R' U' R U2 R' U' R U R'", "U F' U2 L' U L U L' U L F", "U' L U2 L' U2 R U L U' L' U' R'", "U F' R U R' U' R' F R", "R U R' L U' R U R' L' U R U2 R'"], 
	"1":["U R2 U R2' U R U' R U' R2'", "R U2 R' U R U2 R' U2 R U' R'", "U R U' R2 U2 R2 U R2 U R", "U' R U' R' U2 R2 U' L' U R2 U' L", "U2 R U' R' U2 R U' R' U' R U R'", "U R' U' R2 U' R2 U2 R2 U R'", "U' R U R' U2 R U2 R' U' R U2 R'", "U2 R2 U R' U R' U' R2 U' R2"], 
	"0":["R U2 R' U R U' R' U2 R U' R'", "R U2 R' U R U2 R' U' R U2 R'", "U R U R' U2 R U2 R' U2 R U' R'", "U R U R' U2 R U R' U' R U2 R'", "R U' R' U' R U' R' U R U R'", "R U' R' U' R U R' U R U R'"], 
};

var zzf2l = {
	"FR":["R U R' U2 R U' R' U R U' R'", "R U' R' U2 R U' R' / L D' L' U L D L'", "R' U2 R2 U R2 U R", "R U2 R U R' U R U2 R2", "(U2) R2 U2 R' U' R U' R2", "U' R U' R' U' R U2 R' / L' D2 L U2 L' D2 L", "R U2 R' U' R U R'"],
	"FL":["L' U' L U2 L' U L U' L' U L", "R' D R U' R' D' R / L' U L U2 L' U L", "L U2 L2 U' L2 U' L'", "L' U2 L' U' L U' L' U2 L2", "(U2) L2 U2 L U L' U L2", "R D2 R' U2 R D2 R' / U L' U L U L' U2 L", "L' U2 L U L' U' L"],
	"BR":["R' U' R U2 R' U R U' R' U R", "R' U R U2 R' U R / L' D L U' L' D' L", "R U2 R2 U' R2 U' R'", "R' U2 R' U' R U' R' U2 R2", "R2 U' R2 U' R2 U2 R2", "U R' U R U R' U2 R / L D2 L' U2 L D2 L'", "R' U2 R U R' U' R"],
	"BL":["L U L' U2 L U' L' U L U' L'", "R D' R' U R D R' / L U' L' U2 L U' L'", "L' U2 L2 U L2 U L", "L U2 L U L' U L U2 L2", "L2 U L2 U L2 U2 L2", "R' D2 R U2 R' D2 R / U' L U' L' U' L U2 L'", "L U2 L' U' L U L'"],
};

window.algs = {
	//"ZZF2L": zzf2l,
	"TTLL": ttll
	"TTLL (𝝅)": ttllPi
	"TTLL (Swagrid)": ttllSwagrid,
	"TTLL (Legacy, from soncScoot's Document)": ttllLegacy,
	"TTLL (Tao Yu's trainer)": ttllTao,
	"TSLE": tsle,
    "TSLE (Tao Yu's trainer)": tsleTao,
	"OLS (Full)": ols,
	"Summer Variation (Case 1)": sv,
	"OLS Case 2": c2,
	"OLS Case 3": c3,
	"OLS Case 4": c4,
	"Winter Variation (Case 5)": wv,
	"Winter Variation (from the spreadsheet)": wvSonc,
	"OLS Case 6": c6,
	"OLS Case 7": c7,
	"OLS Case 8": c8,
	"OLS Case 9": c9,
	"OLS Case 10": c10,
	"OLS Case 11": c11,
	"OLS Case 12": c12,
	"OLS Case 13": c13,
	"OLS Case 14": c14,
	"OLS Case 15": c15,
	"OLS Case 16": c16,
	"OLS Case 17": c17,
	"OLS Case 18": c18,
	"OLS Case 19": c19,
	"OLS Case 20": c20,
};
